### ISSUE TITLE
Conseil should have (ideally) no partial functions

### ISSUE THREAD

**Issue by ba205** [Cryptonomic/Conseil#103]
One of the comments on our code review was that there are several places in which our code will not terminate on all inputs, and we throw exceptions when we can use concrete types instead. Refactoring the codebase in this way should help the long-term health of the system

**Comment by vishakh** [comment]
Addressed by #151

**Comment by ivanopagano** [comment]
@vishakh I'm trying to better understand why you say that #151 addresses the issue?

Do you mean that it handles part of the problem or it solves it?

As I see it, there are still places where an internal failure on the input is returned as a `500 Internal Server Error` from Conseil. Is it the expected outcome from the frontend/client?

**Comment by ba205** [comment]
Hi @ivanopagano, Vishakh mentioned that at my request. It solves a big chunk of the problem, as APIOperations is a big module, but there may be other partial functions lurking around in other modules.

**Comment by ivanopagano** [comment]
Need to refactor the JsonUtil api to return a possibly failing result of parsing a json string.

It could return a `Try[T]` that have to be handled by the calling code
