### ISSUE TITLE
Add ability to deploy Conseil as a JAR

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#125]
- [ ] Set up Maven publishing
- [x] Set up proper versioning in the code base.

**Comment by ivanopagano** [comment]
to allow publishing on central repository, through sonatype hosting, it's necessary to register cryptonomic as a group on the system, and open a ticket to setup the conseil repository

registration link: https://issues.sonatype.org/secure/Signup!default.jspa
instructions: https://central.sonatype.org/pages/ossrh-guide.html#deployment
cake-solutions blog on sbt publishing: https://www.cakesolutions.net/teamblogs/2012/01/28/publishing-sbt-projects-to-nexus

**Comment by ivanopagano** [comment]
WRT the versioning + realease process:

> I've seen a couple of different strategies, like tagging with git for release and have some plugin do the rest, or we can manually decide to spin out a new release from master

**Comment by ivanopagano** [comment]
While I'm learning about different online tools to simplify the versioning/release cycle I'll put here the outcomes of my talk with Mike for what we would like to achieve exactly:

 -  use some common enough standard for versioning scheme
 - platform versioning should be simple enough for humans to relate to it (like single number and not an unintelligible text)
 - possible proposal `xx.yymm.zzzz` where
   - xx = major number (i.e. `0`, `1`, `2`, ...)
   - yy = year reference
   - mm = month reference
   - zzzz = something that relates to the vcs sources to easily relate the running program with its code
 - run the release process from the CI tool (both web and CLI would be nice to have)
   - available only for authenticated and authorized roles within the CI
   - the CI will execute the scripts with the proper credentials
   - manual operation, no automation
   - "tag" the current `head` on `master` with the new version scheme
   - make a clean build, run tests (unit and integration)
   - package the artifact and release it to sonatype (this involves additional sub-steps to complete)
   - credentials for publishing would only be available in the CI environment, never stored anywhere in the source repo
   - how about the actual [close and  release](https://central.sonatype.org/pages/releasing-the-deployment.html) steps in the sonatype staging env? Should it be done as part of the CI script or handled after a manual check on the staging env?

Possibly useful tools for integrated build+deployment
https://github.com/xerial/sbt-sonatype
https://github.com/ShiftLeftSecurity/sbt-ci-release-early
