### ISSUE TITLE
Implement miscellaneous Scalac code review comments

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#127]
Scalac conducted a Conseil code review in June. This ticket covers all items in the report not covered by other tickets.

**Comment by ivanopagano** [comment]
I've checked the code review doc and verified the following points:

 - Database threads: the connection pool is handled by the underlyng HikariCP based on threads assigned to the AsyncHandler. Such pool is set to `10` which might be a reasonable value for a quad-core machine along the formula provided [here](https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing#connections--core_count--2--effective_spindle_count), which should be applied to thread-count in this case
 - Akka threads: at the moment different PRs are introducing usage of the actor-system dispatcher as default and dedicated thread-pools for specific use cases, so this should be handled
 - Coding best practices are progressively introduced in PRs related to async-database access and block processing refactors
 - Akka Http: currently remapping the `Filter` case class to better match the requests parameters [IN PROGRESS]
 - Use of Strings: will provide classes (a.k.a. newtypes) to wrap strings that should avoid subtle bugs [TODO]
 - Splitting of `TezosNodeOperator` class [TO BE EVALUATED]

The advice related to extraction of SSL termination remains unsatisfied as it involves devops involvement.

**Comment by ivanopagano** [comment]
The last point is deferred to another issue

**Comment by ivanopagano** [comment]
The remaining last point is deferred to separate issue
