### ISSUE TITLE
Add ability to run Lorre for a block interval

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#130]
At the moment, Lorre can only be run from a given block (head or manually specified) back to the genesis block (level zero). This is because all blocks in the database are expected to have a predecessor. 

We should:
- [ ] Relax the database constraint and allow blocks without predecessors
- [ ] Make the start (defaults to head) and end (defaults to level 0) block hashes command line parameters

**Comment by anonymoussprocket** [comment]
Superseded by #213.

**Comment by vishakh** [comment]
Reopening ticket so it rides off #213. 

We now want to existing `depth` command line parameter to Lorre to accept block ranges, e.g. `1000:2500'.

**Comment by vishakh** [comment]
I would now recommend not changing the behaviour of the `depth` argument. Instead, there should be a new argument (e.g. `--headHash`) which allows the optional specification of the hash of the maximum desired block. In combination with `depth` the new argument should allow us to run Lorre for any desired range. 

For example, if I wanted to run Lorre from block 127,000 to 127,100 I would set the the head hash parameter to `BMCUFw5J1ocXibgZifMLGgTeqezZUWtWuZp1j3PLhm2fLnShLqb` and the depth parameter to `100`.
