### ISSUE TITLE
Slick should make batch updates to database, not singular

### ISSUE THREAD

**Issue by ba205** [Cryptonomic/Conseil#140]
Right now, when slick creates queries to update the database, blocks, accounts, etc, entities are processed one by one, instead of in batches. We need to refactor our slick code in APIOperations.scala and TezosDatabaseOperations.scala to remedy this issue, and see if this increases performance.

**Comment by ivanopagano** [comment]
I will check the underlying query to verify if batching is used by slick under the hood
