### ISSUE TITLE
Fix fetchOperations query and add indexes

### ISSUE THREAD

**Issue by ba205** [Cryptonomic/Conseil#153]
The following issues were suggested to be fixed by Diego with regards to database query performance:

[]-Remove usage of COALESCE in fetchOperations query, as it prevents indexes from being used, and is currently a bottleneck for Conseil's performance
[X]-Add these two indexes: 
    -CREATE INDEX ix_operations_kind ON operations (kind);
    -CREATE INDEX ix_operations_timestamp ON operations (timestamp);

**Comment by vishakh** [comment]
Descoped due to Slick restrictions.
