### ISSUE TITLE
Conseil should return 400 when receiving an improper combination of filters

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#157]
While the rest api reads all the incoming parameters and dynamically converts them to a `Filter`, not all combinations are valid and different endpoints allow different combos.

When an invalid one is found an internal `Exception` is thrown that should be converted to a `IllegalArgumentException` if we want the route handler to show the error message as the body of a 400 response

**Comment by vishakh** [comment]
@ivanopagano Is this still a valid ticket?

**Comment by ivanopagano** [comment]
I would close this, it refers to the GET endpoints from V1, if I'm correct, which I don't even know is used anymore...?
