### ISSUE TITLE
Allow delegations to 'null'

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Conseil#164]
We want Galleon users to have the option to delegate to a 'null' address.

In Galleon, users can pick the baker's address at the time of;
1. Origination: When they are about to create a brand new KT1 address
2. Delegation: When they are about to change the bakers address of their KT1 address

So we need 2 functions from Conseil allowing;
1. Originations with empty Delegate addresses -> Originates a KT1 address delegating to null
2. Delegations with empty Delegate addresses -> Changes the baker address of a KT1 address to 'null'

**Comment by vishakh** [comment]
Closed in favor of https://github.com/Cryptonomic/ConseilJS/issues/38.
