### ISSUE TITLE
Expose list of available networks via service call

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#180]
Name it something along the lines of "ListNetworks"

The response should be an array of elements where the attributes are:

- Name: unique internal name that can be used to reference this object
- DisplayName: network name that may be visible to the user
- Platform: enum, currently having a single value - Tezos
- Network: network-specific subtype, in the case of Tezos, one of mainnet, zeronet, alphanet

**Comment by piotrkosecki** [comment]
Done in https://github.com/Cryptonomic/Conseil/pull/186
