### ISSUE TITLE
Expose list of available entities via service call

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#181]
Name it something along the lines of "ListEntityForNetwork", it will take a single parameter which would be a reference to a network as described in #180

The response should be an array of elements where the attributes are:
- Name: unique internal name that can be used to reference this object
- DisplayName: entity name that may be visible to the user
- Count: a recent count of these elements
- Network: network reference

**Comment by piotrkosecki** [comment]
Done in https://github.com/Cryptonomic/Conseil/pull/186
