### ISSUE TITLE
Expose list of available attributes via service call

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#182]
Name it something along the lines of "ListAttributesForEntity", it will take a single parameter which would be a reference to an entity as described in #181.

The response should be an array of elements where the attributes are:
- Name: unique internal name that can be used to reference this object
- DisplayName: attribute name that may be visible to the user
- DataType: enum, hex, binary, date, datetime, string, int, largeint, decimal, boolean
- Cardinality: a count of district values, up to 1M.
- KeyType: enum: non-key, unique key
- Entity: entity reference

**Comment by piotrkosecki** [comment]
Done in https://github.com/Cryptonomic/Conseil/pull/186
