### ISSUE TITLE
Query for distinct values given an attribute

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#183]
Taking an attribute reference (described in #182) return a list of distinct values.

Error conditions:
- query for high-cardinality field
- query for date, or datetime field
- query for any cardinality numeric field

Query for boolean fields should return a canned list: ["True", "False"]

**Comment by piotrkosecki** [comment]
Done in https://github.com/Cryptonomic/Conseil/pull/191
