### ISSUE TITLE
Query definition

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#188]
The URL for this should be: /v2/data/{platform}/{network}/
```javascript
{
    fields: ["", ... ""],
    predicates: [
        {
            field: "",
            operation: "in",
            set: ["", ... ""],
            inverse: "inverse", /* if present, negates the operation */
        }
    ]
}
```
- fields are attributes as described in #182
- operation can be omitted, it will then default to in
- multiple predicates are treated as and operands

**Comment by ivanopagano** [comment]
why define the `fields` array when it can be deduced by the `predicates` elements?

**Comment by piotrkosecki** [comment]
I think what @anonymoussprocket meant by that is `fields` array is about values which are being requested from API(its not like `SELECT *`, its rather `SELECT column1, column2, ...`), and predicates are for filtering.
