### ISSUE TITLE
Switching Accounts Processing to a Diff Approach

### ISSUE THREAD

**Issue by ba205** [Cryptonomic/Conseil#194]
Right now, accounts processing includes getting all accounts referenced by the latest block (every block references all current active accounts) collected by Lorre in our database, and using those account ids to fetch account data from the Tezos RPC interface, stuffing them into an accounts table, and running a process with Lorre to delete all accounts that aren't associated with the last block.

Now, we will move to a diff approach, by using the fact that the all of the operations in the blocks Lorre has captured have references to accounts recently added or changed, so we will only push those to the database at every iteration, doing updates if the account id is already accounted for in the database, inserting otherwise. As a consequence of this change, we will remove account purging functionality, and update APIOperations to not make accounts fetching dependent on being tied to the latest block level.

To do is as follows:
- [ ] We already read operation metadata as a string for any given block. After converting it to an object, we can also use a regex on the actual string to get account ids from the  operation_result field (internal_operation_result field as well, if we're dealing with transactions). Account ids are of the form "tz1*", "tz2*", "tz3*", and "KT1*"
- [ ] Given the fetched account ids, use those to grab account metadata using the Tezos RPC instead of simply fetching all accounts referenced by the block with the highest block level
- [ ] Write database operation to perform insert/update on accounts table, given the account data, depending on whether the account id is already in the table or not
- [ ] change logic in APIOperations module, so that anything that has to do with accounts fetching doesn't require needing the block_level field of an account row to be the maximum block level
- [ ] remove the truncation process from Lorre that truncates accounts not tied to the maximum block level

**Comment by anonymoussprocket** [comment]
This regex may work for you:

```
(tz[1,2,3]|KT1)[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{33}
```
