### ISSUE TITLE
Reference data caching

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#196]
Create an in-memory cache for low-cardinality fields. This would depend on the functionality provided by #183. The cache should contain all distinct values.

There may be a need for an optimization where there is a primary cache of values constructed without any filters, and a secondary cache subject to some generic filters like date=today. For example we could cache accounts that have transacted today.

**Comment by ivanopagano** [comment]
@piotrkosecki is this done?

**Comment by piotrkosecki** [comment]
implemented and merged:
https://github.com/Cryptonomic/Conseil/pull/227
