### ISSUE TITLE
Allow skipping of chain catch-up

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#213]
Create a configuration option for Lorre to skip downloading of chain data from genesis block.

Starting block would be an int where `-1` is genesis block. Running Lorre like this would force it to download process the entire chain, thereby overwriting the existing data.

If the parameter is `0`, that would me catch up, meaning read the last recorded block level from the database and download whatever is missing.

Finally any other positive `n` would mean download the last n blocks starting with head. For example 10 would mean get the head block and the nine prior ones.

The command line parameter should be called "depth".

This work is supersedes #130.

**Comment by ivanopagano** [comment]
@dorians was this actually closed?
