### ISSUE TITLE
Normalize new API URLs

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#214]
/v2/metadata/platforms <- List of available platforms, e.g. Tezos or Ethereum
/v2/metadata/{platform}/networks <-- List of available networks for a given platform, e.g. mainnet or zeronet
/v2/metadata/{platform}/{network}/entities
/v2/metadata/{platform}/{network}/{entity}/attributes
/v2/metadata/{platform}/{network}/{entity}/{attribute}/
- This URL would accept an optional JSON query as specified in #184

/v2/query

Related issues: #180, #181, #182, #184, #188

**Comment by piotrkosecki** [comment]
Here are examples for those endpoints:
https://github.com/Cryptonomic/Conseil/blob/master/doc/MetadataAndQuery.md
