### ISSUE TITLE
Query sort support

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#221]
Add an `orderby` parameter to the query definition.

```
{
    fields: ["", ... ""],
    predicates: [ ... ]
    orderby [
        {
            "field": field_name,
            "direction": "asc | desc"
        }
        ...
    ]
}
```

It should only be possible to `orderby` a field in the result set. `field` as defined in #188

**Comment by piotrkosecki** [comment]
implemented and merged in https://github.com/Cryptonomic/Conseil/pull/224
