### ISSUE TITLE
Find better solution to test Tezos integration

### ISSUE THREAD

**Issue by dorians** [Cryptonomic/Conseil#222]
Right now tests for Tezos integration are based on mocks. It's overcomplicated and should be changed to make these tests more reliable. A possible solution might be to introduce an embedded version of Tezos and rewrite existing tests. This is tricky because we won't be able to stub blocks.

**Comment by vishakh** [comment]
Indeed, embedding a Tezos client would be much better and allow more exhaustive testing. But, as you pointed out, block production is difficult. The objective of our Nautilus project is to provide a solution like this. Unfortunately, that is still a few months away. For now, I recommend extending the mock up as minimally as possible.

@anonymoussprocket @ba205

**Comment by ivanopagano** [comment]
look at related work on #187 too
