### ISSUE TITLE
Query result set limit support

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#223]
Add a `limit` parameter to the query definition.

```
{
    fields: ["", ... ""],
    predicates: [ ... ],
    limit: n,
    ...
}
```

If a limit is not provided, it should default to 10000. Hard limit, at least for now, should be 100000.

**Comment by piotrkosecki** [comment]
implemented and merged in https://github.com/Cryptonomic/Conseil/pull/226
