### ISSUE TITLE
Optimisation of getBlocks method

### ISSUE THREAD

**Issue by dorians** [Cryptonomic/Conseil#229]
We make a first call to the network to get the head block... based on that we recover the additional "count-1" predecessor blocks?
Could a single call to getBlocks be arranged without the need to get a first network response to read the head data?

https://github.com/Cryptonomic/Conseil/pull/217#discussion_r246030987

**Comment by ivanopagano** [comment]
The first block is needed for multiple tasks, and differently used based on which is executed (like catching up with latest missing blocks from chain, or detecting a fork...

In one of my still-wip branch I've found it useful to get the basic block head data once and pass it to any process that needs it. This might solve the issue.

We can keep this in mind even if the branch is not eventually merged.
I'm closing to remove clutter, but please re-open if we see that this becomes a performance issue.
