### ISSUE TITLE
OperationParticipant is not used in Filtering

### ISSUE THREAD

**Issue by ba205** [Cryptonomic/Conseil#231]
In DatabaseQueryExecution, filterOperationParticipants has a bug: rather than do a proper "or" on operationSource and operationDestination, it performs a "short circuit or", that is, if it operationDestination exists, it just uses that, and if it doesn't exist, then it uses operationSource. What we want is to check if either are in set, but also have the option of checking if both are in set.

If <hash> is given as an operationParticipant as a filter, the query should return all records in which <hash> is either an operationSource or an operationDestination.

EDIT: There may be a new bug associated with this. When multiple "operation_kind" filters are used in conjunction with an "operation_participant" query, some may be ignored.

For example, if you give "operation_participant=<hash>&operation_kind=reveal&operation_kind=transaction", it will only show reveals, but if you replace operation_participant with operation_source, both reveals and transactions will show up.

**Comment by ivanopagano** [comment]
The old API will be deprecated soon in favor of v2

This issue will not be solved.

**Comment by ivanopagano** [comment]
Closing as wontfix
