### ISSUE TITLE
Tezos manager pubkey field is different in the schema between alphanet and zeronet

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#237]
On alphanet: `managerPubkey`
On zeronet: `manager_pubkey` (more consistent with the rest)

The new version of operations from PR #232 will count on a specific format, and thus fail if we use the same Conseil between the two networks.

Should we work to handle gracefully the discrepancy or handle it as an error.

@vishakh @anonymoussprocket

**Comment by vishakh** [comment]
We are pretty much abandoning `zeronet` for now so maybe it's best for now to simply support the `alphanet` / `mainnet` version.

**Comment by ivanopagano** [comment]
@vishakh is that to say that the "official" field-name ought to be `managerPubkey`, inconsistently with the all other fields' naming?
