### ISSUE TITLE
Consider Chimney to reduce boilerplate in DatabaseConversions

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#238]
I think this library could help us avoid some of boilerplate code in this object: https://github.com/scalalandio/chimney

What do you think?

_Originally posted by @piotrkosecki in https://github.com/Cryptonomic/Conseil/pull/232_

**Comment by vishakh** [comment]
Could you list a couple of places in our code base where this might be useful?

**Comment by ivanopagano** [comment]
@vishakh essentially in the `DatabaseConversions` object

**Comment by piotrkosecki** [comment]
I've already used it in the transformation from `ApiQuery` -> `Query`. Basically this lib allowed me to replace copying optional fields with `getOrElse`, with just `Query().patchWith(this)` and as Ivano mentioned I think it could be useful in `DatabaseConversions` where there is a lot of transformations happening.
