### ISSUE TITLE
Increase Lorre's resilience by syncing using some staging area

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#240]
The idea would be to have 2 separate processes to 
- read from tezos node and store unprocessed json into a temporary staging area (postgres table, document store, kv-store, cache?)
- write to conseil's tables the feed that reads from the staging area

Expected gains:
- decoupling of rate/throughput for syncing and for writing to conseil
- robust handling of any possible parsing error arising from unexpected json, without disrupting the sync process
- ?

Added costs:
- handling of fork events might become more complex (or unexpectedly simpler)
- handling of a separate storage, which might grow temporarily when json processing has any consistent issue that halts the draining of data in the staging space
- ?

**Comment by vishakh** [comment]
Closing because the Pencroff project was started up.
