### ISSUE TITLE
Tezos genesis block no longer parsed correctly

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#260]
The Tezos genesis block for `alphanet` does not have balance updates:

```json
{
   "protocol":"PrihK96nBAFSxVL1GLJTVhu9YnzkMFiBeuJRPA8NwuZVZCE1L6i",
   "chain_id":"NetXgtSLGNJvNye",
   "hash":"BLockGenesisGenesisGenesisGenesisGenesisb83baZgbyZe",
   "header":{ },
   "metadata":{
      "protocol":"PrihK96nBAFSxVL1GLJTVhu9YnzkMFiBeuJRPA8NwuZVZCE1L6i",
      "next_protocol":"Ps6mwMrF2ER2s51cp9yYpjDcuzQjsc2yAz8bQsRgdaRxw4Fk95H",
      "test_chain_status":{
         "status":"not_running"
      },
      "max_operations_ttl":0,
      "max_operation_data_length":0,
      "max_block_header_length":105,
      "max_operation_list_length":[

      ]
   },
   "operations":[

   ]
}
```

Yet, the `BlockHeaderMetadata` object expects this as a mandatory field and Lorre dies. 

We must ensure that Lorre is able to successfully process the genesis block (and others).

In addition, let us fix the reporting of parsing exceptions so the faulty payload is printed out to console. 
For example, we should immediately print out the faulty JSON at:

https://github.com/Cryptonomic/Conseil/blob/e598bf1a837064b33b8f50f590dcb77924520812/src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeOperator.scala#L269

Maybe something like:

```scala
case Left(error) =>
            println(s"This block payload did not parse! \n ${json}")
            Future.failed(error)
```

The same applies to parsing of all kinds of data.  

Genesis block data should probably be thoroughly checked in our unit tests as well.

**Comment by anonymoussprocket** [comment]
Please add an integration test as part of the solution to this issue
