### ISSUE TITLE
Lorre shutdown after initial blocks downloaded into Postgres

### ISSUE THREAD

**Issue by leenpaws** [Cryptonomic/Conseil#263]
Update: After initial commit, postgres essentially works to build indices while lorre seems to stop, might need to increase number of available threads(speculative) as previously we used to run a custom config file with num_threads = 16, now we default to application.conf which only has 10.  errors posted show that the accounts table seems to crap out once postgres is done building indices and lorre starts picking up the latest blocks.

**Comment by ivanopagano** [comment]
Might be related to
https://github.com/dnvriend/akka-persistence-jdbc/issues/177

**Comment by ivanopagano** [comment]
suggested fix will be to include maxConnection with a value equal to numThreads on the db config

**Comment by leenpaws** [comment]
current status is 10 and 10 for threads and connections respectively is too low, changed to 20 and 20, however, lorre still drops connection after accounts update finish, logs are in conseil chat on 2/22 between 1750 and 1908 EST

**Comment by leenpaws** [comment]
it's possible/probable that this may not have to do with the number of connections and threads as after the accounts table update, lorre picks up the neglected blocks and then for some reason shuts down, during the time that it's picking up the blocks two connections to the db are open, one connection is deleting info, another is adding info, will add screenshots

**Comment by leenpaws** [comment]
![db_state_at_time_of_malfunction](https://user-images.githubusercontent.com/18505064/53278182-c6a2c200-36d5-11e9-9fdc-8bdd74180458.png)
[dev2_lorre_debug.pdf](https://github.com/Cryptonomic/Conseil/files/2896267/dev2_lorre_debug.pdf)

**Comment by ivanopagano** [comment]
I'm about to submit a PR trying to smooth out the issue, by providing additional information during the account handling part of the process, and batching the processing itself.
Additionally, I removed a transactional boundary that allowed the upserts for accounts only to succeed or fail as a whole.

From the logs of local testing, that I'm attaching, we can explain the long period with a single connection to the db actually doing work. It's a query that essentially needs to read all ids on the account checkpoint table (tracks which accounts have been referenced by a new block), and then to select the entry referred by the highest available block hash.
Such query can become pretty heavy it seems, it needs to fetch a significant number of distinct account ids (16830 in my test case), and order the results to keep the highest, from all those in the checkpoint table (I lost the exact number but they should be an order of magnitude bigger).
This operation took between 40-45 minutes on my machine.
After that "pause", the rest of the process continues pretty much streamlined. 

```log
12:21:07.683 [lorre-system-akka.actor.default-dispatcher-24] INFO  tech.cryptonomic.conseil.Lorre$ - Selecting all accounts touched in the checkpoint table, this might take a while...                                                                                                                                                                                                                                                                                                                                                                        
[...]
13:04:52.542 [lorre-system-akka.actor.default-dispatcher-22] INFO  tech.cryptonomic.conseil.Lorre$ - I loaded all stored account references and will proceed to fetch updated information from the chain                                                                                                                                                                                                                                                                                                                                                       
```

**This is not yet explaining why the process on nautilus failed consistently
 after storing the accounts**

**Comment by ivanopagano** [comment]
Closing, given that
- the current memory loading of secondary data (accounts and delegates) should have mitigated the issue of using the persistent checkpoint data
- data from checkpoint should now be paged to lighten up the loading operation
