### ISSUE TITLE
Use property checking and random generators for database tests

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#271]
Given the current repetition in self-made code to generate random data for database operations testing, it might be worthwhile to investigate an approach based on property checking, using [scalacheck](http://scalacheck.org/), removing the ad-hoc generation needed for each separate class needed in the tests.

**Comment by vishakh** [comment]
Is this still something that could be beneficial?

**Comment by ivanopagano** [comment]
Very low-priority, it's about making some tests easier to maintain and more meaningful possibly.
I don't think we have bandwidth for this now.
