### ISSUE TITLE
Parsing parameters expressed as an array

### ISSUE THREAD

**Issue by dorians** [Cryptonomic/Conseil#282]
Expression:``parse[MichelsonExpression](json)("""[{"int":"0"},{"int":"2"},{"int":"4"},{"int":"8"},{"int":"16"}]""")`` fails. 

It should be probably encoded as: ``{0, 2, 4, 8}``

**Comment by ivanopagano** [comment]
You meant `parse[MichelsonExpression]("""[{"int":"0"},{"int":"2"},{"int":"4"},{"int":"8"},{"int":"16"}]""")`?  
I guess it should convert to `{ 0 ; 2 ; 4 ; 8 }`

**Comment by dorians** [comment]
Oh my! Two mistakes in two sentences. Right! :)
