### ISSUE TITLE
Use Slick metadata API for the metadata route in Conseil

### ISSUE THREAD

**Issue by piotrkosecki** [Cryptonomic/Conseil#286]
Currently `metadata` route uses hardcoded slick `TableQuery` and caching on routes.

The goal is to implement `metadata` functionality using Slick metadata API, so tables won't be no longer hardcoded and explore different ways of caching required data.

**Comment by ivanopagano** [comment]
@piotrkosecki is this done?

**Comment by piotrkosecki** [comment]
implemented and merged:
https://github.com/Cryptonomic/Conseil/pull/297
