### ISSUE TITLE
Lorre fails to correctly store Account updates

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#291]
Might be related to #263 

Some failure in the accounts updates fetch and db write process seems to fail the operation as a whole with the fairly relevant possibility of losing such account recent values, especially on Lorre bootstrap of data.

**Comment by dorians** [comment]
Maybe it's connected to this change: https://github.com/Cryptonomic/Conseil/pull/283/files#diff-a1f87af6ceeb51a87d285c983a5f9ef2R323

**Comment by ivanopagano** [comment]
> Maybe it's connected to this change: https://github.com/Cryptonomic/Conseil/pull/283/files#diff-a1f87af6ceeb51a87d285c983a5f9ef2R323

I'm not sure but it might've happened before... I'm essentially thinking that the michelson can fail to parse and ignore the failure (which might make sense), with the unwanted side-effect of failing the whole account fetching and storage without stopping the process.

Do you think it makes sense, @dorians ?

**Comment by ivanopagano** [comment]
There seems to be some problem with how Jackson parses accounts containing a script.
Looks like it fails to read the script object as a String, because it's not a valid Json String, i.e. starts with an open brace.

I'll then switch that last bit of parsing to circe, hoping the semi-manual decoding would serve

**Comment by ivanopagano** [comment]
The final analysis leads to the following explanation.

The issue is that json parsing couldn't correctly read the "script" inside accounts as simple text, while considering it a formally valid json object, not a valid json string.
This parsing failure would fail the whole account processing step whenever an account with a script was found, therefore losing track of the fact.
That meant we would lose some updates on accounts, too.
