### ISSUE TITLE
Lorre should print out processing information for accounts

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#301]
Lorre should print out processing information for accounts just as it does for blocks. Especially after a full-chain download, it's difficult to see how far account fetching has progressed. Here is some example output:

```
18:57:16.997 [lorre-system-akka.actor.default-dispatcher-14] INFO  tech.cryptonomic.conseil.Lorre$ - Completed processing 99.52% of total requested blocks
18:57:16.997 [lorre-system-akka.actor.default-dispatcher-14] INFO  tech.cryptonomic.conseil.Lorre$ - Estimated time to finish is around 2 minutes
18:58:22.674 [lorre-system-akka.actor.default-dispatcher-1453] INFO  tech.cryptonomic.conseil.Lorre$ - Wrote 395 blocks to the database, checkpoint stored for account updates
18:59:45.535 [lorre-system-akka.actor.default-dispatcher-59] INFO  tech.cryptonomic.conseil.Lorre$ - Wrote 0 voting data records to the database
18:59:45.535 [lorre-system-akka.actor.default-dispatcher-14] INFO  tech.cryptonomic.conseil.Lorre$ - Completed processing 100.00% of total requested blocks
18:59:45.535 [lorre-system-akka.actor.default-dispatcher-14] INFO  tech.cryptonomic.conseil.Lorre$ - Processing latest Tezos data for updated accounts...
18:59:45.563 [lorre-system-akka.actor.default-dispatcher-14] INFO  tech.cryptonomic.conseil.Lorre$ - Selecting all accounts touched in the checkpoint table, this might take a while...
```

The time is now 00:45 the day after but it's impossible to say how account fetching is doing. The only evidence I see for active processing is Postgres is maxing out a CPU core.

**Comment by vishakh** [comment]
Is this feasible, @ivanopagano? If so, how much effort do you think this involves?

**Comment by vishakh** [comment]
I see that account processing information is indeed being written. Is there a reason why it wouldn't be the case in the run whose log I pasted above?

**Comment by ivanopagano** [comment]
I mentioned in a different issue that it's a slightly different problem we have here, one that I'm gonna fix soon, indeed.
The progress of accounts' processing is currently logged as for blocks.

The operation taking so much is not processing of each account per-se, but the preparatory query to fetch the actual accounts that need updates.
The query is terribly inefficient and I will rewrite that part to read separately each account-id and process it concurrently.

**Comment by vishakh** [comment]
Leaving the ticket open for now pending the solution @ivanopagano described.
