### ISSUE TITLE
Overriding data

### ISSUE THREAD

**Issue by dorians** [Cryptonomic/Conseil#309]
When I run ``Lorre`` twice with a parameter ``--depth 10`` the second run fails with the following error: 

> Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "blocks_hash_key"

We need better error (or maybe not error at all if data from tezos matches data from db) and possibly parameter ``--override`` which would be really useful for debugging.

**Comment by ivanopagano** [comment]
That's interesting as a proposal, but in general I think that before starting to change things to accomodate ad-hoc situations, we should thing a bit about what would be the correct handling of overrides and inconsistencies when running against a range of levels, over an existing dataset.

I'm not even sure it makes sense right now to invest in this effort, as we mainly want the feature to be used as a testing and debugging scenario.
