### ISSUE TITLE
Store a storage field

### ISSUE THREAD

**Issue by dorians** [Cryptonomic/Conseil#315]
We do need to store storage in PostgreSQL from the following structure:
```
object Scripted {
  final case class Contracts(
    storage: Micheline,
    code: Micheline
  )
}
```

Right now we store only ``code``.

**Comment by ivanopagano** [comment]
Is this done? @dorians @vishakh

**Comment by dorians** [comment]
I would leave this one open because we need to do the same for accounts. I started working on it but paused because the metadata task has a higher priority.
