### ISSUE TITLE
Consume paid_storage_size_diff field with operations

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Conseil#330]
Invoking and deploying a smart contract sometimes requires a payment to be made to increase the storage size. This information is listed under operation metadata with the name `paid_storage_size_diff`. This information is not recorded in Conseil. Can we please add? Also adding `storage_size` would be very nice.

Here is an example of an origination operation. Note that **some** transaction operations have the same field.

**Operation Group ID:** oot6P2D7TSKbwjtDbPBsETXvJnZCWkRAk3ZqfwPb1BrnKUz3yJ5

The result Tezos Node returns:

![](https://user-images.githubusercontent.com/37525692/55583316-99dbc480-56ef-11e9-888e-ae5b76ea4367.png)

The result in Conseil:

![Screen Shot 2019-04-09 at 5 04 04 PM](https://user-images.githubusercontent.com/37525692/55835179-7ea2f780-5ae9-11e9-8ed5-f12d75dd3b18.png)

**Comment by ivanopagano** [comment]
@umurb Clear, I'll add those.
In general we're not yet exporting all fields, especially from operation results

**Comment by umurb** [comment]
Understood. I believe adding these two fields would be sufficient for now. Thanks!
