### ISSUE TITLE
Stackoverflow on compilation

### ISSUE THREAD

**Issue by dorians** [Cryptonomic/Conseil#351]
Running ``sbt compile`` causes ``[error] (Compile / compileIncremental) java.lang.StackOverflowError``. 

We can make a workaround increasing the memory for a stack: ``sbt compile -J-Xss32m``. 

We should investigate the problem and figure it out why we need so much memory.

**Comment by dorians** [comment]
I spent some time trying to figure out why do we need so much memory for a stack. Apparently, we are using really heavy tools and that memory is just needed to use them. 

https://github.com/pureconfig/pureconfig/issues/390
https://circe.github.io/circe/codecs/known-issues.html
https://github.com/milessabin/shapeless/issues/852

**Comment by ivanopagano** [comment]
so it was just a question of time before the issue would've exploded?

**Comment by dorians** [comment]
@ivanopagano Exactly

**Comment by ba205** [comment]
@anonymoussprocket sbt compile works locally for me.
