### ISSUE TITLE
Supplementary metadata continued

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#354]
Allow definition of arbitrary metadata keys, consider the following:

```
value-map: {0: "Yay", 1: "Nay", 2: "Pass"}
```

This could be used to describe the low-cardinality enum in ballots.ballot. UIs can be built to interpret this information the way that suites them. All Conseil would need to do is pass this data along.

Additionally, it should be possible to override any metadata key. For example, while some numbers in the schema may appear to be `int`, they are functionally `decimal` with some sort of scaling. Take as an example accounts.balance, while stored as in, it is actually µtz. This value would be more meaningfully displayed as n/1000000.
```
scale: 6
```
Would indicate to the UI how to display such a value.

Overriding datatype further would help identify special strings like addresses.
```
dataType: "address"
```

**Comment by dorians** [comment]
@anonymoussprocket Could you give me an example of how it should work? Where exactly should `value-map` be defined?

**Comment by anonymoussprocket** [comment]
```
          ballots {
            visible: true
            attributes {
              pkh {
                display-name: "Address"
                visible: true
              }
              ballot {
                display-name: "Vote"
                visible: true
                value-map: {0: "Yay", 1: "Nay", 2: "Pass"}
              }
              block_id {
                display-name: "Block Hash"
                visible: true
              }
              block_level {
                visible: true
              }
            }
          }

**Comment by dorians** [comment]
Is that a response you want to have?

```
[
...
  {
    "name": "ballot",
    "displayName": "Vote",
    "dataType": "String",
    "cardinality": 0,
    "keyType": "NonKey",
    "entity": "ballots",
    "valueMap": {0: "Yay", 1: "Nay", 2: "Pass"}
  }
...
```

**Comment by anonymoussprocket** [comment]
Yes, except ballot dataType should be a number and cardinality would be 3.

**Comment by anonymoussprocket** [comment]
scale and data-type overrides

```
accounts {
    visible: true,
    attributes {
        account_id {
            description: "Sometimes referred to as 'public key hash', the address is a unique account identifier"
            display-name: "Address"
            placeholder: "tz1..."
            visible: true
            data-type: "hash"
        }
        ...
        balance {
            visible: true
            scale: 6
        }
    }
}
