### ISSUE TITLE
Create `delegates' and 'delegated_contracts' tables

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#357]
Conseil currently does not store information about bakers other than their weight in the governance process (`bakers` table). We should therefore add this information.

Using the Tezos RPC call `/chains/main/blocks/{blockid}/context/delegates/{address}` we should populate a table called `delegates`. The `delegated_contracts` field in the returned data is an array so its contents should be stored in a `delegated_contracts` table which links to the parent table `delegates`.

**Comment by ivanopagano** [comment]
I expect the delegated contracts to be the same referenced by blocks, therefore they should look something like

```json
{ "manager": "pkh",
    "balance": 1000,
    "spendable": true,
    "delegate": { "setable": true, "value": "pkh" },
    "script": { "code" : <michelin code>, "storage": <micheline code> },
    "counter": 401
}
```
?

**Comment by ivanopagano** [comment]
and @ba205 @vishakh 
where is the connection between a block and the delegates we're looking for?
Should I collect pkh from the block's operations?

**Comment by ivanopagano** [comment]
btw, I'll ask in Riot later, yet I can't seem to find if there's a json-schema description of the involved objects

**Comment by BrianGuo** [comment]
I'm curious about the decision to store `delegated_contracts` as a separate table, when `delegated_contracts` is a subset of the `accounts` table and the relationship between the delegate and the delegator could potentially be codified as a property of some `accounts` table (I'm assuming accounts is a table).

**Comment by vishakh** [comment]
@BrianGuo The `accounts` table indeed already contains delegation information. We are creating `delegated_contracts` as a redundancy.

**Comment by ivanopagano** [comment]
@vishakh 
should we think of renaming the bakers' table to explicitly say it's about the governance process, and use `delegate_bakers` for the baking delegates?
Will this make things more clear?

**Comment by ivanopagano** [comment]
Like, `bakers_rolls` and `baking_delegates`
