### ISSUE TITLE
Query predicate requirements

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#389]
Using metadata for a particular entity (new metadata functionality may need to be added) reject queries that do not contain either a filter on a date-like field (`block level` for example) or a key field (not necessarily primary key in a SQL sense).

**Comment by vishakh** [comment]
Could you explain the rationale for this change?

**Comment by anonymoussprocket** [comment]
Since temporal fields are indexed, queries with predicates on those fields will perform better. I would like to enforce that.

**Comment by piotrkosecki** [comment]
implemented and merged:
https://github.com/Cryptonomic/Conseil/pull/406
