### ISSUE TITLE
Add support for calculated metrics

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#403]
So far, Conseil reproduced simply what it encounters on the blockchain. However, in order to support block explorers and other tools, it must also record calculated information in its database.

A table called `network_metrics` should be created with the following columns:
- Metric
- Source
- Window (m)
- Function
- Value
- Unit
- Timestamp
- Block level

Here is an example record for the 24-hour endorsement rate on the blockchain:

`Endrosement_rate | Blockchain | 1440 | Avg | 98.6 | Pct | 1559708711 | 200000` 

Similarly, average fees could also be inserted into this table:

`Fees_High | Blockchain | 360 | Avg+Stddev | 2006 | uxtz | 1559708711 | 200,000` 

Functions for calculating these metrics would be part of a separate process with each function on its own timer.

The initial metrics to be populated into this table would be endorsement rates and average fees over various time frames.

The windows above are supposed to be recalculated on window anniversaries and non-overlapping.

**Comment by anonymoussprocket** [comment]
- This process should not be part of the critical path for data loading.
- It may be worth while recording the source of the data.
- Having the window expressed in standard terms would allow queries on that column.
- A block level reference would help relate this data to other records in the database.
- It would make sense to run this process on the hot-standby env and then bulk copy the data into the hot-live env.
- How often would the window be recalculated?
- How would forks affect this process? Multiple windows would need to be ru-run in that case.

**Comment by vishakh** [comment]
>     * This process should not be part of the critical path for data loading.

Updated

>     * It may be worth while recording the source of the data.

Updated

>     * Having the window expressed in standard terms would allow queries on that column.

Would you like to use an enum or something else, e.g. start and stop timestamps?

>     * A block level reference would help relate this data to other records in the database.

Window-based metrics wouldn't make sense with a block level reference, right? Or can you give a concrete example?

>     * It would make sense to run this process on the hot-standby env and then bulk copy the data into the hot-live env.

We would need to strongly ensure the two environments are in sync. This might be quite challenging from the infrastructure perspective. 

>     * How often would the window be recalculated?

Each function would have a custom timer defined in a config file.

>     * How would forks affect this process? Multiple windows would need to be ru-run in that case.

As the metrics are constantly recalculated, they would become accurate shortly after the fork. Fixing the older metrics retrospectively might be too complex for now so we could keep it out of scope. However, we could establish some kind of manual process for invalidating records.

**Comment by anonymoussprocket** [comment]
-
- I meant more specific source of data, like the table that participated in its calculation.
- Window would be expressed in seconds or millis.
- If it has a timestamp of the calculation, it can have a block level. This could be the upper end of the window for which the result was calc'ed.
- 
- I don't suppose the windowed items would be re-calc'ed every block (though maybe?)
-

**Comment by vishakh** [comment]
Updated spec as discussed.

**Comment by ivanopagano** [comment]
Is this to be configurable, as you seem to mention?

Should the computation definition be configurable too, like a name that would elsewhere refer to some pluggable scala class?
This would allow to easily integrate new metrics and to easily tune the timing and operations, at the cost of being far less flexible.

**Comment by dorians** [comment]
We should consider using an ELK stack for that. Gathering those metrics by hand would be not scalable (it's really hard to calculate those metrics between different instances). Other point is that it's more elastic to keep rare data and do calculations on demand. WDYF?

**Comment by ivanopagano** [comment]
Not sure what you mean...
I'd say that to reduce load we'd better keep only pre-computed aggregates, instead of source data to extract later on and compute upon.
But I might be misinterpreting your comment @dorians

**Comment by vishakh** [comment]
Out of scope for now.
