### ISSUE TITLE
Make accounts table temporal

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#404]
Currently there is no way to view account history as Lorre updates account data in place in the database. We must therefore make the accounts table temporal. 

We can accomplish this by adding an `asof` column to the `accounts` table. Here is a caricature:

```
account_id | balance | asof | block_level
tz1kjdjk41o421kj2 | 20203437843 | 4pm | 500k
tz1kjdjk41o421kj2 | 20203437850 | 2pm | 475k
```

A query to get the latest balance for a given account would be of this form:

```sql
select * from accounts where account_id = 'tz1kjdjk41o421kj2' where asof<= now() order by asof desc limit 1;
```

A query to get the balance as of a given time would be of this form:

```sql
select * from accounts where account_id = 'tz1kjdjk41o421kj2' where asof<= 3 pm order by asof desc limit 1;
```

Finally, account history can be obtained with a simple query:

```sql
select * from accounts where account_id = 'tz1kjdjk41o421kj2' 
```

**Comment by anonymoussprocket** [comment]
I propose that all ledger-style tables (blocks, operations, operation_groups, ballots, balance_updates) are made partitioned, and all status tables are made temporal (accounts, rolls).

**Comment by vishakh** [comment]
Agreed.

**Comment by ivanopagano** [comment]
does the timestamp of temporal data refers to a timestamp in the corresponding block being added?

I anticipate a lot of rework to handle forks, ouch...

**Comment by vishakh** [comment]
@ivanopagano The timestamp could be any indicator of when the record was added. For example, block level or block hash should do. Does that make fork handling easier?

**Comment by vishakh** [comment]
TODO: Put together a document which expresses the above and the following:

- What query do we run to get a snapshot of all current active accounts?
- What query do we run to get a snapshot of all active accounts at a given time (by either timestamp or block level)?

Considerations:
- Temporal fields should be labeled as such in metadata.
- An incoming query must have a temporal field selected in order to query non-current data.
- All temporal tables should have at the minimum timestamp and block level as fields.

Families of queries:
- Give me certain records from the latest snapshot.
- Give me certain records from a past snapshot.
- Give me certain records from the entire table. 
- Give me all accounts touched in block 17.

**Comment by godenzim** [comment]
this feature is highly needed for our block explorer (tezblock). Can this be included in the next release?

**Comment by vishakh** [comment]
@piotrkosecki As discussed, the data in the database look good. However, we need to make some changes to the API.

By default, temporal tables should behave the exact same as regular tables. 

To run a temporal query, there should be a new query field called `snapshot` which should be non-null. Then the records should come back as of that timestamp:

```json
snapshot: {
type: "asof"
value: 1572018897
}
```
After the implementation of this ticket, we should be able to easily ask these questions thorugh the API in a performant manner:

Get the balance of an account at a specific block level.
Get the balance of an account at a specific timestamp.
Get all records for an account over a range of blocks
