### ISSUE TITLE
Keep latest block level in Lorre memory

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#408]
On every cycle, Lorre fetches the highest stored block level from the db.

We can skip this by keeping this value in memory between cycles, so that the db read should be needed only at restart

**Comment by ivanopagano** [comment]
Do you think it's a worthwhile improvement @vishakh ?

**Comment by vishakh** [comment]
@ivanopagano It depends on the complexity of the logic. Having each iteration start from scratch has a lot of elegance and error minimization behind it. Do you think this will be a light touch or otherwise?

**Comment by bhaskarkishore** [comment]
@ivanopagano : Just following up here, Any thoughts on @vishakh 's comment?

**Comment by ivanopagano** [comment]
Didn't think about it that much, would need to revisit the idea

**Comment by ivanopagano** [comment]
I will probably reconsider this right now as soon as we've closed #581
