### ISSUE TITLE
Working with PG during build

### ISSUE THREAD

**Issue by ksemaev** [Cryptonomic/Conseil#432]
Please tell if acces to PG during build is only used in testing purposes? Can I just spinup empty postgres during build, and safely delete it after build is done?

**Comment by vishakh** [comment]
No, you need it for running Conseil as well. All data is stored in Postgres. 

Please join our developer chat for more infromation - https://matrix.to/#/!rUwpbdwWhWgKINPyOD:cryptonomic.tech?via=cryptonomic.tech&via=matrix.org&via=tzchat.org.

**Comment by ksemaev** [comment]
@vishakh TY! I understand that you need it, but could it be 2 different databases - one used during build, and another to which I connect after build? 
So the question is - do you need access to real production database during build (run migrations or whatever), or temporary PG setup is enough, as it is used only for testing purposes?

**Comment by ksemaev** [comment]
NM, it seems that only embedded PG used during build for test purposes
