### ISSUE TITLE
build in docker

### ISSUE THREAD

**Issue by ksemaev** [Cryptonomic/Conseil#435]
I've created this simple dockerfile for building purposes:

```
################################
### Builder image
################################
FROM ubuntu:18.04 as builder

ENV CONSEIL_VERSION=2019-june-release-8 \
    SCALA_VERSION=2.13.0

RUN apt update && \
    apt install -y \
    software-properties-common \
    openjdk-8-jdk \
    postgresql \
    postgresql-contrib \
    gnupg \
    wget

RUN wget www.scala-lang.org/files/archive/scala-$SCALA_VERSION.deb && \
    dpkg -i scala-$SCALA_VERSION.deb

RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 && \
    apt update && \
    apt install -y \
    sbt

RUN wget -O- https://github.com/Cryptonomic/Conseil/archive/$CONSEIL_VERSION.tar.gz | tar xz && \
    mv Conseil-$CONSEIL_VERSION /conseil
        
WORKDIR /conseil

RUN mkdir /home/postgres && \
    chown postgres:postgres /home/postgres && \
    su -c "/usr/lib/postgresql/10/bin/initdb -D /home/postgres" postgres && \
    su -c "/usr/lib/postgresql/10/bin/pg_ctl  -o \"-F -p 5433\" -D /home/postgres start" postgres && \
    sbt clean assembly -J-Xss32m
```

But as it tries to install  it's own`EmbeddedPostgres(Version.V9_5_15)` during scala build - it all fails. Can we somehow install that embedded PG only if needed and use PG connection string?

**Comment by ksemaev** [comment]
The latest error I get with my own PG on board is: 

> Extract /root/.embedpostgresql/postgresql-9.5.15-1-linux-x64-binaries.tar.gz START
> ..................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Extract /root/.embedpostgresql/postgresql-9.5.15-1-linux-x64-binaries.tar.gz DONE
> 11:01:42.035 [pool-7-thread-7] WARN  r.y.q.e.postgresql.PostgresProcess - Possibly failed to run initdb:
> initdb: cannot be run as root
> 
> Please log in (using, e.g., "su") as the (unprivileged) user that will
> 
> own the server process.
> 
> 
> 11:02:01.960 [pool-7-thread-7] ERROR r.y.q.e.postgresql.PostgresProcess - Failed to read PID file (File '/tmp/postgresql-embed-5dd3d745-08c9-4569-9813-be86e0a8c6ca/db-content-d5babcfc-cab8-4137-b496-0befeb8a7bad/postmaster.pid' does not exist)
> java.io.FileNotFoundException: File '/tmp/postgresql-embed-5dd3d745-08c9-4569-9813-be86e0a8c6ca/db-content-d5babcfc-cab8-4137-b496-0befeb8a7bad/postmaster.pid' does not exist
> 	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:299)
> 	at org.apache.commons.io.FileUtils.readLines(FileUtils.java:1783)
> 	at org.apache.commons.io.FileUtils.readLines(FileUtils.java:1819)
> 	at ru.yandex.qatools.embed.postgresql.PostgresProcess.onAfterProcessStart(PostgresProcess.java:256)
> 	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:116)
> 	at ru.yandex.qatools.embed.postgresql.AbstractPGProcess.<init>(AbstractPGProcess.java:19)
> 	at ru.yandex.qatools.embed.postgresql.PostgresProcess.<init>(PostgresProcess.java:68)
> 	at ru.yandex.qatools.embed.postgresql.PostgresExecutable.start(PostgresExecutable.java:25)
> 	at ru.yandex.qatools.embed.postgresql.PostgresExecutable.start(PostgresExecutable.java:13)
> 	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:108)
> 	at ru.yandex.qatools.embed.postgresql.EmbeddedPostgres.start(EmbeddedPostgres.java:194)
> 	at tech.cryptonomic.conseil.tezos.InMemoryDatabase.beforeAll(InMemoryDatabase.scala:91)
> 	at tech.cryptonomic.conseil.tezos.InMemoryDatabase.beforeAll$(InMemoryDatabase.scala:81)
> 	at tech.cryptonomic.conseil.tezos.TezosDatabaseOperationsTest.beforeAll(TezosDatabaseOperationsTest.scala:21)
> 	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
> 	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
> 	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
> 	at tech.cryptonomic.conseil.tezos.TezosDatabaseOperationsTest.run(TezosDatabaseOperationsTest.scala:21)
> 	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
> 	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
> 	at sbt.TestRunner.runTest$1(TestFramework.scala:113)
> 	at sbt.TestRunner.run(TestFramework.scala:124)
> 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
> 	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
> 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
> 	at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
> 	at sbt.TestFunction.apply(TestFramework.scala:294)
> 	at sbt.Tests$.processRunnable$1(Tests.scala:347)
> 	at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
> 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
> 	at sbt.std.Transform$$anon$4.work(System.scala:67)
> 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
> 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
> 	at sbt.Execute.work(Execute.scala:278)
> 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
> 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
> 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> 2019-06-26 11:02:16.879 UTC [767] ERROR:  insert or update on table "accounts" violates foreign key constraint "accounts_block_id_fkey"
> 2019-06-26 11:02:16.879 UTC [767] DETAIL:  Key (block_id)=(no-block-hash) is not present in table "blocks".
> 2019-06-26 11:02:16.879 UTC [767] STATEMENT:   insert into "accounts" ("account_id","block_id","manager","spendable","delegate_setable","delegate_value","counter","script","storage","balance","block_level") select $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11 where not exists (select 1 from "accounts" where "account_id"=$12)
> 2019-06-26 11:02:19.192 UTC [784] ERROR:  insert or update on table "delegates" violates foreign key constraint "delegates_block_id_fkey"
> 2019-06-26 11:02:19.192 UTC [784] DETAIL:  Key (block_id)=(no-block-hash) is not present in table "blocks".
> 2019-06-26 11:02:19.192 UTC [784] STATEMENT:   insert into "delegates" ("pkh","block_id","balance","frozen_balance","staking_balance","delegated_balance","deactivated","grace_period","block_level") select $1,$2,$3,$4,$5,$6,$7,$8,$9 where not exists (select 1 from "delegates" where "pkh"=$10)
> java.lang.BootstrapMethodError: call site initialization exception
> 	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
> 	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
> 	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
> 	at slick.compiler.MergeToComprehensions.mergeSortBy$1(MergeToComprehensions.scala:81)
> 	at slick.compiler.MergeToComprehensions.$anonfun$convert$21(MergeToComprehensions.scala:68)
> 	at slick.compiler.MergeToComprehensions.$anonfun$convert$21$adapted(MergeToComprehensions.scala:68)
> 	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:356)
> 	at slick.compiler.MergeToComprehensions.mergeTakeDrop$1(MergeToComprehensions.scala:68)
> 	at slick.compiler.MergeToComprehensions.mergeTakeDrop$1(MergeToComprehensions.scala:42)
> 	at slick.compiler.MergeToComprehensions.$anonfun$convert$20(MergeToComprehensions.scala:68)
> 	at slick.compiler.MergeToComprehensions.$anonfun$convert$20$adapted(MergeToComprehensions.scala:68)
> 	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:331)
> 	at slick.compiler.MergeToComprehensions.mergeTakeDrop$1(MergeToComprehensions.scala:68)
> 	at slick.compiler.MergeToComprehensions.createTopLevel$1(MergeToComprehensions.scala:265)
> 	at slick.compiler.MergeToComprehensions.convert1$1(MergeToComprehensions.scala:281)
> 	at slick.compiler.MergeToComprehensions.convert(MergeToComprehensions.scala:301)
> 	at slick.compiler.MergeToComprehensions.$anonfun$apply$2(MergeToComprehensions.scala:29)
> 	at slick.ast.ClientSideOp$.mapResultSetMapping(ClientSideOp.scala:23)
> 	at slick.compiler.MergeToComprehensions.$anonfun$apply$1(MergeToComprehensions.scala:28)
> 	at slick.compiler.CompilerState.map(QueryCompiler.scala:230)
> 	at slick.compiler.MergeToComprehensions.apply(MergeToComprehensions.scala:28)
> 	at slick.compiler.QueryCompiler.$anonfun$runPhase$1(QueryCompiler.scala:79)
> 	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
> 	at slick.ast.SymbolNamer.use(Symbol.scala:111)
> 	at slick.compiler.QueryCompiler.runPhase(QueryCompiler.scala:78)
> 	at slick.compiler.QueryCompiler.$anonfun$runPhases$9(QueryCompiler.scala:75)
> 	at scala.collection.TraversableOnce.$anonfun$foldLeft$1(TraversableOnce.scala:160)
> 	at scala.collection.TraversableOnce.$anonfun$foldLeft$1$adapted(TraversableOnce.scala:160)
> 	at scala.collection.Iterator.foreach(Iterator.scala:941)
> 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
> 	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:160)
> 	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:158)
> 	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1429)
> 	at slick.compiler.QueryCompiler.runPhases(QueryCompiler.scala:75)
> 	at slick.compiler.QueryCompiler.run(QueryCompiler.scala:53)
> 	at slick.compiler.QueryCompiler.run(QueryCompiler.scala:47)
> 	at slick.basic.BasicProfile$API.streamableQueryActionExtensionMethods(BasicProfile.scala:56)
> 	at slick.basic.BasicProfile$API.streamableQueryActionExtensionMethods$(BasicProfile.scala:55)
> 	at slick.jdbc.JdbcProfile$$anon$1.streamableQueryActionExtensionMethods(JdbcProfile.scala:67)
> 	at tech.cryptonomic.conseil.tezos.TezosDatabaseOperations$.$anonfun$getLatestAccountsFromCheckpoint$3(TezosDatabaseOperations.scala:194)
> 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
> 	at scala.collection.Iterator.foreach(Iterator.scala:941)
> 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
> 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
> 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
> 	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
> 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
> 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
> 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
> 	at tech.cryptonomic.conseil.tezos.TezosDatabaseOperations$.$anonfun$getLatestAccountsFromCheckpoint$2(TezosDatabaseOperations.scala:193)
> 	at slick.basic.BasicBackend$DatabaseDef.$anonfun$runInContextInline$1(BasicBackend.scala:171)
> 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
> 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
> 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
> 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
> Caused by: java.lang.OutOfMemoryError: Metaspace
> 	at sun.misc.Unsafe.defineAnonymousClass(Native Method)
> 	at java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:326)
> 	at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:194)
> 	at java.lang.invoke.LambdaMetafactory.altMetafactory(LambdaMetafactory.java:474)
> 	at java.lang.invoke.LambdaForm$DMH/1543974463.invokeStatic_L4_L(LambdaForm$DMH)
> 	at java.lang.invoke.LambdaForm$BMH/129498568.reinvoke(LambdaForm$BMH)
> 	at java.lang.invoke.LambdaForm$MH/784967179.invoker(LambdaForm$MH)
> 	at java.lang.invoke.LambdaForm$MH/394771492.invokeExact_MT(LambdaForm$MH)
> 	at java.lang.invoke.CallSite.makeSite(CallSite.java:325)
> 	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
> 	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
> 	at slick.compiler.MergeToComprehensions.mergeSortBy$1(MergeToComprehensions.scala:81)
> 	at slick.compiler.MergeToComprehensions.$anonfun$convert$21(MergeToComprehensions.scala:68)
> 	at slick.compiler.MergeToComprehensions.$anonfun$convert$21$adapted(MergeToComprehensions.scala:68)
> 	at slick.compiler.MergeToComprehensions$$Lambda$11271/1803409710.apply(Unknown Source)
> 	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:356)
> 	at slick.compiler.MergeToComprehensions.mergeTakeDrop$1(MergeToComprehensions.scala:68)
> 	at slick.compiler.MergeToComprehensions.mergeTakeDrop$1(MergeToComprehensions.scala:42)
> 	at slick.compiler.MergeToComprehensions.$anonfun$convert$20(MergeToComprehensions.scala:68)
> 	at slick.compiler.MergeToComprehensions.$anonfun$convert$20$adapted(MergeToComprehensions.scala:68)
> 	at slick.compiler.MergeToComprehensions$$Lambda$11270/1649664735.apply(Unknown Source)
> 	at slick.compiler.MergeToComprehensions.mergeCommon(MergeToComprehensions.scala:331)
> 	at slick.compiler.MergeToComprehensions.mergeTakeDrop$1(MergeToComprehensions.scala:68)
> 	at slick.compiler.MergeToComprehensions.createTopLevel$1(MergeToComprehensions.scala:265)
> 	at slick.compiler.MergeToComprehensions.convert1$1(MergeToComprehensions.scala:281)
> 	at slick.compiler.MergeToComprehensions.convert(MergeToComprehensions.scala:301)
> 	at slick.compiler.MergeToComprehensions.$anonfun$apply$2(MergeToComprehensions.scala:29)
> 	at slick.compiler.MergeToComprehensions$$Lambda$11266/349647826.apply(Unknown Source)
> 	at slick.ast.ClientSideOp$.mapResultSetMapping(ClientSideOp.scala:23)
> 	at slick.compiler.MergeToComprehensions.$anonfun$apply$1(MergeToComprehensions.scala:28)
> 	at slick.compiler.MergeToComprehensions$$Lambda$11265/1002866224.apply(Unknown Source)
> 	at slick.compiler.CompilerState.map(QueryCompiler.scala:230)
> 2019-06-26 11:02:37.226 UTC [800] LOG:  unexpected EOF on client connection with an open transaction
> Exception in thread "ScalaTest-dispatcher" java.lang.BootstrapMethodError: call site initialization exception
> 	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
> 	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
> 	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
> 	at org.scalatest.DispatchReporter$Propagator.run(DispatchReporter.scala:204)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.OutOfMemoryError: Metaspace
> [error] java.lang.BootstrapMethodError: call site initialization exception
> [error] 	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
> [error] 	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
> [error] 	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
> [error] 	at sbt.EvaluateTask$.convertCyclicInc(EvaluateTask.scala:476)
> [error] 	at sbt.EvaluateTask$.$anonfun$transformInc$1(EvaluateTask.scala:467)
> [error] 	at scala.util.Either$LeftProjection.map(Either.scala:569)
> [error] 	at sbt.EvaluateTask$.transformInc(EvaluateTask.scala:466)
> [error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:424)
> [error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:438)
> [error] 	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:99)
> [error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:355)
> [error] 	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:97)
> [error] 	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:111)
> [error] 	at sbt.internal.Aggregation$.$anonfun$applyTasks$1(Aggregation.scala:67)
> [error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
> [error] 	at sbt.internal.Aggregation$.$anonfun$evaluatingParser$11(Aggregation.scala:212)
> [error] 	at sbt.internal.Act$.$anonfun$actParser0$3(Act.scala:435)
> [error] 	at sbt.Command$.process(Command.scala:181)
> [error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
> [error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
> [error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
> [error] 	at sbt.State$$anon$1.process(State.scala:250)
> [error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
> [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
> [error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
> [error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
> [error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
> [error] 	at sbt.io.Using.apply(Using.scala:22)
> [error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
> [error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
> [error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
> [error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
> [error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
> [error] 	at sbt.xMain.run(Main.scala:89)
> [error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
> [error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
> [error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
> [error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
> [error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
> [error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
> [error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
> [error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
> [error] 	at xsbt.boot.Boot.main(Boot.scala)
> [error] Caused by: java.lang.InternalError: BMH.reinvoke=Lambda(a0:L/SpeciesData<L>,a1:L,a2:L)=>{
> [error]     t3:L=Species_L.argL0(a0:L);
> [error]     t4:L=MethodHandle.invokeBasic(t3:L,a1:L,a2:L);t4:L}
> [error] 	at java.lang.invoke.MethodHandleStatics.newInternalError(MethodHandleStatics.java:127)
> [error] 	at java.lang.invoke.LambdaForm.compileToBytecode(LambdaForm.java:660)
> [error] 	at java.lang.invoke.LambdaForm.prepare(LambdaForm.java:635)
> [error] 	at java.lang.invoke.MethodHandle.<init>(MethodHandle.java:461)
> [error] 	at java.lang.invoke.BoundMethodHandle.<init>(BoundMethodHandle.java:58)
> [error] 	at java.lang.invoke.BoundMethodHandle$Species_L.<init>(BoundMethodHandle.java:211)
> [error] 	at java.lang.invoke.BoundMethodHandle$Species_L.make(BoundMethodHandle.java:224)
> [error] 	at java.lang.invoke.BoundMethodHandle.makeReinvoker(BoundMethodHandle.java:141)
> [error] 	at java.lang.invoke.DirectMethodHandle.rebind(DirectMethodHandle.java:137)
> [error] 	at java.lang.invoke.MethodHandle.bindArgumentL(MethodHandle.java:1317)
> [error] 	at java.lang.invoke.MethodHandle.bindTo(MethodHandle.java:1277)
> [error] 	at java.lang.invoke.MethodHandleImpl.makePairwiseConvertByEditor(MethodHandleImpl.java:221)
> [error] 	at java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:194)
> [error] 	at java.lang.invoke.MethodHandleImpl.makePairwiseConvert(MethodHandleImpl.java:380)
> [error] 	at java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:776)
> [error] 	at java.lang.invoke.MethodHandle.asType(MethodHandle.java:761)
> [error] 	at java.lang.invoke.MethodHandleImpl$AsVarargsCollector.asTypeUncached(MethodHandleImpl.java:508)
> [error] 	at java.lang.invoke.MethodHandle.asType(MethodHandle.java:761)
> [error] 	at java.lang.invoke.CallSite.makeSite(CallSite.java:323)
> [error] 	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
> [error] 	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
> [error] 	at sbt.EvaluateTask$.convertCyclicInc(EvaluateTask.scala:476)
> [error] 	at sbt.EvaluateTask$.$anonfun$transformInc$1(EvaluateTask.scala:467)
> [error] 	at scala.util.Either$LeftProjection.map(Either.scala:569)
> [error] 	at sbt.EvaluateTask$.transformInc(EvaluateTask.scala:466)
> [error] 	at sbt.EvaluateTask$.run$1(EvaluateTask.scala:424)
> [error] 	at sbt.EvaluateTask$.runTask(EvaluateTask.scala:438)
> [error] 	at sbt.internal.Aggregation$.$anonfun$timedRun$4(Aggregation.scala:99)
> [error] 	at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:355)
> [error] 	at sbt.internal.Aggregation$.timedRun(Aggregation.scala:97)
> [error] 	at sbt.internal.Aggregation$.runTasks(Aggregation.scala:111)
> [error] 	at sbt.internal.Aggregation$.$anonfun$applyTasks$1(Aggregation.scala:67)
> [error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
> [error] 	at sbt.internal.Aggregation$.$anonfun$evaluatingParser$11(Aggregation.scala:212)
> [error] 	at sbt.internal.Act$.$anonfun$actParser0$3(Act.scala:435)
> [error] 	at sbt.Command$.process(Command.scala:181)
> [error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
> [error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
> [error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
> [error] 	at sbt.State$$anon$1.process(State.scala:250)
> [error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
> [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
> [error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
> [error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
> [error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
> [error] 	at sbt.io.Using.apply(Using.scala:22)
> [error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
> [error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
> [error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
> [error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
> [error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
> [error] 	at sbt.xMain.run(Main.scala:89)
> [error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
> [error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
> [error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
> [error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
> [error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
> [error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
> [error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
> [error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
> [error] 	at xsbt.boot.Boot.main(Boot.scala)
> [error] Caused by: java.lang.OutOfMemoryError: Metaspace
> The command '/bin/sh -c mkdir /home/postgres &&     chown postgres:postgres /home/postgres &&     su -c "/usr/lib/postgresql/10/bin/initdb -D /home/postgres" postgres &&     su -c "/usr/lib/postgresql/10/bin/pg_ctl -o \"-F -p 5433\" -D /home/postgres start" postgres &&     sbt clean assembly -J-Xss32m' returned a non-zero code: 1
> ERROR: Job failed: command terminated with exit code 1

**Comment by ivanopagano** [comment]
Hello, the last part of your dockerfile runs the assembly `sbt` task to package the app.

```bash
RUN mkdir /home/postgres && \
    chown postgres:postgres /home/postgres && \
    su -c "/usr/lib/postgresql/10/bin/initdb -D /home/postgres" postgres && \
    su -c "/usr/lib/postgresql/10/bin/pg_ctl  -o \"-F -p 5433\" -D /home/postgres start" postgres && \
    sbt clean assembly -J-Xss32m
```

This in turns will run the "test-suite", which currently runs an "embeddded-postgres" instance based on a local directory, which needs `su` access to properly work.

I guess that running sbt as `su` should solve the issue, if possible

```bash
RUN mkdir /home/postgres && \
    chown postgres:postgres /home/postgres && \
    su -c "/usr/lib/postgresql/10/bin/initdb -D /home/postgres" postgres && \
    su -c "/usr/lib/postgresql/10/bin/pg_ctl  -o \"-F -p 5433\" -D /home/postgres start" postgres && \
    su -c "sbt clean assembly -J-Xss32m"
```

**Comment by ksemaev** [comment]
Well it didn't work, but since you provide .jar as a release artifact - I don't care anymore
