### ISSUE TITLE
Lorre multiple warnings with  exhausted input

### ISSUE THREAD

**Issue by ksemaev** [Cryptonomic/Conseil#443]
When I started Lorre against my tezos node - I receive a lot of such messages:

```
18:34:32.414 [lorre-system-akka.actor.default-dispatcher-37] WARN  t.c.conseil.tezos.TezosNodeOperator - I fetched baker rolls json from tezos node that I'm unable to decode:
io.circe.ParsingFailure: exhausted input
```

Is that fine, or something is wrong there?

**Comment by ivanopagano** [comment]
There's already WIP to reduce those warnings from the logs, for innocuous cases (which is generally 100% of what we see there).
We kept the logging available till now to have some way to lookout for unusual or unexpected cases, but you can expect those warnings to disappear in the near future.

In particular, the voting data was not present in the initial part of the chain, hence we see empty content returned for a while when Lorre syncs from the beginning with the tezos node.

**Comment by ivanopagano** [comment]
Please consider closing the issue, if the answer was satisfying @ksemaev

**Comment by ksemaev** [comment]
TY, got it
