### ISSUE TITLE
Add correlation ids to Lorre's calls to improve tracing of requests

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#448]
As part of this additional operational addition, we should properly configure the logging libraries. Right now we simply use the akka logger to write on stdout, with no specific configuration underlying adapter (mostly we use typesafe's scala logging)

**Comment by bhaskarkishore** [comment]
@ivanopagano : Can you please expand on what you are proposing? Concrete examples would be appreciated.

**Comment by ivanopagano** [comment]
The logging configuration files are now at least minimally configured on `master` branch, so we're basically covered on that.

Yet we might want to figure out how to properly do tracing of requests without the "traditional" pre-canned solutions that rely on having a single thread sticked to each request.
The existing easy solutions rely on akka/lightbend logging and implicit passing of some context.

I'm not sure we might want to stick to using akka or not for the far future, as we're introducing more pieces of the typelevel platform (which is a bit at odds with akka).

I did some quick investigation on alternatives but couldn't find anything ready out-of-the-box

**Comment by anonymoussprocket** [comment]
Is some sort of request object passed all the way through? Can we added a uuid to it?

**Comment by ivanopagano** [comment]
Now there's no "correlation object" passed, and I've no clear picture yet of what's the best way for us currently. I need to make a few experiments first to understand which is the most viable solution

**Comment by vishakh** [comment]
@ivanopagano Is this still something that could be beneficial?

**Comment by ivanopagano** [comment]
Long-standing issue, it would need addressing eventually, but it's not on our roadmap for the near future, so I'd close this.
Eventually re-open it as needed.
