### ISSUE TITLE
Add block level and block hash indexes to rolls table

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#454]
The `rolls` table has no indexes defined on it. As new records are appended to the table per block, the data has become impossible to query. We should therefore add indexes on the columns `block_id` and `block_level` for the table.

**Comment by ivanopagano** [comment]
Was this closed as part of #536 ?

@ba205 @anonymoussprocket

**Comment by vishakh** [comment]
RIP rolls table.
