### ISSUE TITLE
Switch accounts table to contain historical data

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#470]
In order to prepare for the full implementation of #404, we must first have a realistic dataset we can use for our investigations. For this work, we need to make the `accounts` table temporal by inserting new records for new data rather than updating the existing data. The code can stay on a branch while the DB testing is going on and could later be merged into `master` as part of the #404 effort.

**Comment by vishakh** [comment]
The code so far is looking good in the staging environment and we now have a historical accounts table. 

This seems to be the best way to query the table with sub-second performance:

```sql
select 
	s.* 
from 
	(
		select 
			*, rank() 
		over 
			(partition by account_id order by asof desc) as r 
		from 
			accounts_history where asof <= '2018-07-01'
	) s 
where 
	s.r = 1;
```

The required columns can be added to the first `select` and the required predicates can be added to the `where` clause. The date `2019-07-01` can be substituted with any other date and the data returned will be valid from that point. 

The next step is to include `accounts_history` in the API logic and allow queries against it. API queries should take an additional field called `asof` (applicable only to temporal tables) which the user can use to specify the `asof` used for the above query. If no `asof` is supplied for a temporal table query, the default value should be the current timestamp.

**Comment by ivanopagano** [comment]
Maybe I'm not required to understand. I'm not familiar with rank and partitioning sql.

From what I see the previous query is reading account data from those with date previous to a specific value and using the ordering via date to pick only the most recent within the given upper bound.
Still I can't see why we're choosing only `s.r = 1`.
If rows are partitioned by `account_id`, I expect only the first account found to appear?
Or is it supposed to pick only one entry per account_id?

Will it be possible to show an example result from such a query?
