### ISSUE TITLE
Lorre stuck on duplicate key value

### ISSUE THREAD

**Issue by ksemaev** [Cryptonomic/Conseil#481]
Both June and July versions of Lorre are stucked on error:

>  [lorre-system-akka.actor.default-dispatcher-14] ERROR tech.cryptonomic.conseil.Lorre$      - Could not fetch blocks from client
> java.sql.BatchUpdateException: Batch entry 0 insert into "operation_groups" ("protocol","chain_id","hash","branch","signature","block_id")  values (Giant list of values) was aborted: ERROR: duplicate key value violates unique constraint "OperationGroups_pkey"
>   Detail: Key (hash)=(oonGLsoguD7ciz3CEhTBmvbnXAFAm3DQ8KLKhBnpVfCD2BTNCNP) already exists.  Call getNextException to see other errors in the batch.

> Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "OperationGroups_pkey"
>   Detail: Key (hash)=(oonGLsoguD7ciz3CEhTBmvbnXAFAm3DQ8KLKhBnpVfCD2BTNCNP) already exists.
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)

Can you please advice?

**Comment by vishakh** [comment]
@ksemaev Looks like you hit a chain reorg. Currently, we are fixing these manually. Support for forks is under development and should be released soon.

**Comment by ksemaev** [comment]
@vishakh TY for explaining. Can you provide steps for such manual fixes?

**Comment by vishakh** [comment]
Responded to you on Riot.

**Comment by ksemaev** [comment]
Yep, suggested fix worked, TY
