### ISSUE TITLE
Losing connection to node causes Lorre to get stuck

### ISSUE THREAD

**Issue by ksemaev** [Cryptonomic/Conseil#502]
I did a restart of my coin node, which ended with those logs on lorre:

> [WARN] [08/05/2019 11:22:22.957] [lorre-system-akka.actor.default-dispatcher-27] [lorre-system/Pool(shared->http://tezos-1.tezos.coin-nodes:8732)] [7 (WaitingForResponseEntitySubscription)] Response entity was not subscribed after 5 seconds. Make sure to read the response entity body or call `discardBytes()` on it. GET /chains/main/blocks/BLdDxk8NikM2v8CwsEqDQCgBGBNzYGtDP9eNX9ZdK36HHLTckmf/context/delegates/tz1iZEKy4LaAjnTmn2RuGDf2iqdAQKnRi8kY Empty -> 200 OK Default(24079 bytes) [WARN] [08/05/2019 11:22:27.136] [lorre-system-akka.actor.default-dispatcher-36] [lorre-system/Pool(shared->http://tezos-1.tezos.coin-nodes:8732)] [5 (WaitingForResponseEntitySubscription)] Response entity was not subscribed after 5 seconds. Make sure to read the response entity body or call `discardBytes()` on it. GET /chains/main/blocks/BLdDxk8NikM2v8CwsEqDQCgBGBNzYGtDP9eNX9ZdK36HHLTckmf/context/delegates/tz1PesW5khQNhy4revu2ETvMtWPtuVyH2XkZ Empty -> 200 OK Default(12028 bytes)

`java.lang.IllegalStateException: Substream Source cannot be materialized more than once`

Can we please consider handling such cases? For me it would be perfect if app just died, but some reconnect policy could also work. TY!

**Comment by ivanopagano** [comment]
As mentioned in the riot channel, we might want to implement a connection failure to tezos node during Lorre's cycles and configure out to react via configuration:
- shutdown the system and notify the cause
- retry connection to the tezos node, as Lorre already does at startup
