### ISSUE TITLE
Parametrize Tezos chains

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#507]
The Tezos network undergoes protocol upgrades as part of its governance period. Once the network votes in favour of a protocol amendment proposal, the corresponding binary is run in the background by the Tezos network on a test chain. 

We already run queries of this form to query the active (main) chain:

`https://tezos-prod.cryptonomic-infra.tech:443/chains/main/blocks/head`

If we want to instead query the test chain, we modify the query slightly:

`https://tezos-prod.cryptonomic-infra.tech:443/chains/test/blocks/head`

In order to properly test our end to end stack against imminent protocol environments, we would like to run a separate `staging` environment where all data is fetched from the `test` chain and all transactions are sent to the `test` chain as well.

For Conseil, this means the chain name must be parametrized everywhere. The configuration file should accept a new item called `platforms.{platform}.{network}.node.chain`, for example `platforms.tezos.mainnet-test.node.chain: test`. This value should be used by Lorre for all its queries to the Tezos node.

**Comment by ivanopagano** [comment]
I only have a note to make about naming. `chain` is a very bloated term in this context.
Would it be useful to use a more specific variant, like `chain-env`, `chain-variant`, or similar?

**Comment by dorians** [comment]
Right now Lorrie can be run only for one platform and one network only. When querying using Conseil we can provide both platform and network but we only check if they're present in configuration and not disabled by overriding metadata. I believe that this is not a final solution. To do this task as described in the description we should change that behavior and provide many databases to keep data (or parametrize each table with platform and network). Or maybe we don't want to do this at all and remove network and platform parameters from Conseil? 

For now, I just parameterized Lorrie without introducing additional parameters in Conseil (which would be ignored anyway). There is no way to override that using override metadata mechanism. 
@anonymoussprocket, is that ok for now?
