### ISSUE TITLE
Allow cross-predicate OR operation

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#516]
Create syntax to enable an OR condition between predicates. Currently it can only be AND. Only support a single-level nesting along the lines of `(predicate or predicate) and predicate` and `(predicate and predicate) or predicate`.

- Predicate group may contain more than two predicates.
- There may be multiple predicate groups.

**Comment by anonymoussprocket** [comment]
One idea:

```
{
  "fields": [...],
  "predicates": [
    { "field", "set", "operation", "inverse", "group": "group A"}, // P0
    { "field", "set", "operation", "inverse", "group": "group A"}, // P1
    { "field", "set", "operation", "inverse", "group": "group B"}, // P2
    { "field", "set", "operation", "inverse", "group": "group C"}, // P3
    { "field", "set", "operation", "inverse", "group": "group C"} // P4
  ],
  "predicateGroups": [
    {"group": "group A", "condition": "OR"},
    {"group": "group B", "condition": "AND"},
    {"group": "group C", "condition": "AND"},
  ]
  "orderBy": [...],
  "aggregation": [...],
  "limit": 50
}
```

Logically this would be interpreted as `or (P0 and P1) and (P2) and (P3 and P4)`, clearly this can be simplified into `(P2 and P2 and P4) or (P0 and P1)`, therefore `predicateGroups` does not need to list AND-condition groups, nor do they need to be separated. Group naming functionality should not be exposed to the end-user of the libraries.

**Comment by m-kus** [comment]
Perhaps it's better to have nested predicates with extra operation `or`
```
{
  "fields": [...],
  "predicates": [{
    "operation": "or",
    "predicates": [ # default is AND (and backward compatible)
      {"operation": "or", "predicates": [{...}, {...}]},
      {...},
      {...}
    ]
  }],
  "orderBy": [...],
  "aggregation": [...],
  "limit": 50
}
```

**Comment by piotrkosecki** [comment]
I think @m-kus have a point. This schema is much easier to understand and backward compatible. 
What do you think @anonymoussprocket ?

**Comment by godenzim** [comment]
We are developing a block explorer that uses Conseil and this feature would help us a lot by reducing the number of requests we need to perform. @m-kus  proposed syntax looks good. Is it in any way possible to have this implemented sooner rather than later?

**Comment by ivanopagano** [comment]
If we're not under strict necessity of doing nesting, a one-level OR can be expressed simply by using named groups above, and implicit operation between (OR) and within groups (AND).

e.g.

```
field", "set", "operation", "inverse", "group": "group A"}, // P0
    { "field", "set", "operation", "inverse", "group": "group A"}, // P1
    { "field", "set", "operation", "inverse", "group": "group B"}, // P2
    { "field", "set", "operation", "inverse", "group": "group C"}, // P3
    { "field", "set", "operation", "inverse", "group": "group C"} // P4
  ],
  "orderBy": [...],
  "aggregation": [...],
  "limit": 50
}
 
```
would become
`(P0 AND P1) OR (P2) OR (P3 AND P4)`

Creating a recursive nested structure will imply quite a work to do to properly implement and test.
On the other hand this might already be enough for most situations?

**Comment by godenzim** [comment]
@ivanopagano That would satisfy our immediate need. If that is easier to implement and would make this feature available sooner, then I would say that is good enough for now.
