### ISSUE TITLE
Move application resources out of doc

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#532]
`conseil.sql` and `conceil.yaml` need to be moved into `src/main/resources/`

**Comment by ivanopagano** [comment]
Can I ask some clarification about this?

1. The src/main/resources folder content will be packaged into the application jar, is that intended as a way to distribute the content with the artifact?
2. conceil.yaml seems to be a OpenApi descriptor which is currently generated by the Conseil app itself, based on code-defined endpoints and docs. Is it still relevant at all?
3. the sql schema definition file is used to generate both local testing dockerized postgres instances and to auto-generate database modeling code from Slick. Moving the file will impact those tasks

**Comment by anonymoussprocket** [comment]
The doc folder is for documentation only, not for assets that code may reference or deployment scripts might need. I'm also interested in removing `/doc` and migrating all documentation into the docsify format as we started in `/docs`. Ticket #391 is about that, I'll close this as a dupe of that one.
