### ISSUE TITLE
Suggestion: Dockerhub Automated Build

### ISSUE THREAD

**Issue by tulpenhaendler** [Cryptonomic/Conseil#533]
consider publishing official conseil Images via docker hub automated build:

an automated build would look like this:

https://hub.docker.com/r/tuliptools/tezos

Images get built by dockerhub on every push to the master branch of the source repo,
If you check the builds section on dockerhub, you can see exactly which commit was used to build the image, so that way people can verify what is in the image and only have to trust dockerhub, as opposed to some custom ci ( jenkins.. ) that pushses images to dockerhub

In addition to be more secure, this is also less work for you, you need a dockerhub account, link it with your github account and create the repo, dockerhub will handle the rest and build automatically on every push to github, no ci stuff on your side needed.

**Comment by tulpenhaendler** [comment]
Just fyi, i did a dockerhub build like this on:

https://hub.docker.com/r/tuliptools/conseil

but will remove once there is an official one by you guys.

**Comment by vishakh** [comment]
Closing as a DockerHub build step has been added.
