### ISSUE TITLE
DB namespaces

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#540]
Create a namespace for the Tezos tables that Lorre & Conseil use.

**Comment by ivanopagano** [comment]
Can be a common namespace? I can't think of anything different

**Comment by bhaskarkishore** [comment]
@ivanopagano : I believe the intention of this ticket is to support `Schema`s other than the default public.

**Comment by ivanopagano** [comment]
I think I got that... simply asking if moving to a `tezos` namespace is enough, for both conseil & lorre?

**Comment by anonymoussprocket** [comment]
Yep, that's the idea, so we can isolate data better.
