### ISSUE TITLE
P005 message field changes

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#545]
- [ ] `source` should be changed to PublicKeyHash type, as tz accounts are not contracts and currently source is of type ContractId
- [ ] mark the removed `origination` fields as nullable: `manager_pubkey`, `spendable`, `delegable`

**Comment by ivanopagano** [comment]
From the upgrade docs I also saw 
- the rpc results includes a new field in the “endorsement” operation, namely “slot”, that specifies the first slot of the endorser.

Should that be included too?

Note: I was checking from the `/describe` endpoint for operations on current zeronet and I don't see any such field in the json-schema for "endorsement" I must admit

**Comment by anonymoussprocket** [comment]
Yes, that should be included, good catch, thank you
