### ISSUE TITLE
Make conseil work without api keys

### ISSUE THREAD

**Issue by tulpenhaendler** [Cryptonomic/Conseil#552]
It would be nice if we could have a setting in the config that disables API keys.
I am not sure that is possible at the moment.

Use Case:
Running Conseil on a private network, or in some larger setup where conseil is not exposed publicly but only to internal applications, I have been doing dummy keys for now but it would be a bit more elegant without keys at all. Also, it would help with running public conseil instances, in that use case someone would just put nginx or traefik in front of conseil to do rate-limiting or load balancing etc, and users could connect to the public instance without keys.

**Comment by tulpenhaendler** [comment]
I tried with apikeys: [""] in config,
but i get the error:

```
Request is missing required HTTP header 'apikey'
```

**Comment by anonymoussprocket** [comment]
Closed in favor of #553.
