### ISSUE TITLE
Level in Balance_Updates Table is inaccurate

### ISSUE THREAD

**Issue by ba205** [Cryptonomic/Conseil#559]
There are currently null values for 'level' in the balance_updates table, as well as potentially inaccurate level data for those which are not null. This should be corrected to be in line with the Blocks and Operations table, based on where the balance_update data was recorded.

**Comment by vishakh** [comment]
@ba205 Was this fixed already?

**Comment by ivanopagano** [comment]
Any news here? Need support?
