### ISSUE TITLE
Ensure Conseil/Lorre can run in a container

### ISSUE THREAD

**Issue by leenpaws** [Cryptonomic/Conseil#563]
We often experience issues running Conseil / Lorre in containers. Lorre dies periodically with no clear pattern.

Conseil / Lorre should be run locally in a Docker container, preferably using `nautilus.sh`, against a remote Tezos node. As needed, any bugs should be fixed and Docker-related issues identified. Also, logging should be enhanced so that the nature of the underlying issues is clear. 

As part of this process, Lorre should be synced from scratch against the Tezos `mainnet`.

**Comment by ivanopagano** [comment]
I have problems running a local `nautilus.sh` script as long as [this issue](https://github.com/Cryptonomic/Nautilus/issues/32) is still unsolved: I'm on macos.

**Comment by ivanopagano** [comment]
Sure, I'll work with a locally-made docker image

**Comment by ivanopagano** [comment]
I have completed a whole sync against our development environment node.

Didn't experience any failures during the process.

@leenpaws 
Close if it's enough as a check.
