### ISSUE TITLE
Babylon upgrade

### ISSUE THREAD

**Issue by roccomuso** [Cryptonomic/Conseil#589]
How Conseil API are gonna be affected by the upcoming Babylon upgrade?

**Comment by anonymoussprocket** [comment]
Work for Protocol 005 support is in the [master-p005](https://github.com/Cryptonomic/Conseil/tree/master-p005) branch. Conseil will make the new data available as specified. Do you have a more specific question?

**Comment by roccomuso** [comment]
There will be a new version released once babylon is operational?

**Comment by anonymoussprocket** [comment]
Yep, there will be a release.
