### ISSUE TITLE
Remove delegate column from accounts table

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#593]
As part of the recent proto05 changes, the `accounts` table was modified. However, we ended up with two redundant columns, `delegate_value` and `delegate`. The newer `delegate` column should be removed and all data that was going to it should instead go to the existing `delegate_value` column.

**Comment by pascuin** [comment]
If you go with `delegate_value` please make sure that the index introduced in #525 for `delegate` is not being missed.
