### ISSUE TITLE
Split embedded database tests from unit tests

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#598]
Since the unit tests are run on each packaging, the docker build fails for some OS configuration, because the embedded DB seems to be problematic (possibly due to the underlying flapdoodle library solution).

If this proves to be the root cause, we might want to simply move the tests involving a real db process to work, into the existing `it` integration tests.

Such tests would first need be run and tested over the CI pipeline to see if everything works fine.

The ensuing codebase should also provide a smoother dev cycle, given the uTests suite would run much faster, and could be possibly parallelized too.

**Comment by vishakh** [comment]
As part of this effort, we should move from the current Yandex library to its recommended alternative: https://www.testcontainers.org/modules/databases/.

**Comment by vishakh** [comment]
Let's first simply migrate libraries. If the mock DB unit tests still cause a problem we can move them to the IT folder. My concern is nobody will look at these tests if we don't keep them as "required".
