### ISSUE TITLE
Add cycle and governance period to baking and endorsement rights tables

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#600]
Add cycle and period fields. This will allow for some interesting statistics to be presented.

Period in this case is the same as period index in the blocks table.

**Comment by godenzim** [comment]
Yes, this improvement would be very helpful to us.

**Comment by vishakh** [comment]
@ba205 The new columns should be called `cycle` and `governance_period`. These can be fetched from the block data.
