### ISSUE TITLE
Operations.period is not populated correctly

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#601]
Period field is only set for proposal operations. It should be available for all operations. This is the same information as period index in blocks.

**Comment by vishakh** [comment]
@anonymoussprocket `period` right now has a specific semantic meaning for proposals. We could rename the existing column to `proposal_period` and add a new generic `governance_period` column.

**Comment by vishakh** [comment]
Superseded by #565.
