### ISSUE TITLE
Add data for upcoming blocks to the baking and endorsement rights tables

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#602]
Baking and endorsing rights tables need to show future assignments.

**Comment by vishakh** [comment]
@anonymoussprocket @godenzim How many futures blocks of rights should we store?

**Comment by vishakh** [comment]
@pasculin ^^

**Comment by vishakh** [comment]
@pascuin ^^

**Comment by pascuin** [comment]
Probably the upcoming 5 cycles would make sense.

**Comment by vishakh** [comment]
Some background
- A Tezos cycle consists of 4096 blocks
- The rights to bake (create) or endorse a block are known in advance
- At any point, we know the baking and endorsing rights for the current cycle and the five coming ones.

The goal of this task is to store in the database the all known future baking and endorsing rights. We currently only store the baking and endorsing rights for the current block.

We would like to add a process in Lorre that is outside of its main loop. Every time interval (let's say one hour), a function is executed such that:
- It calculates the maximum block for which rights are available.
  - Use the `/chains/main/blocks/head` Tezos RPC call to figure out the current `cycle`.
  - Get the remaining blocks in the current cycle: `4096 - cycle`
  - Add the number of blocks in the next five cycles: `4096 * 5`
  - Use above to calculate max available block for rights: `(4096 - cycle) + 4096 * 5`
- It obtains the maximum block for which rights are available in the database
- For all blocks for which rights are available but not written in the database, it fetches baking and endorsing rights from the Tezos nodes and writes them to the database. 

It should be very clear in the logs which entries are coming from this process vs. the ones coming from the regular Lorre main loop so debugging is easy. 

In the future, we may decide to spin off this process as a separate executable.

**Comment by ba205** [comment]
>   * Use the `/chains/main/blocks/head` Tezos RPC call to figure out the current `cycle`.
>   * Get the remaining blocks in the current cycle: `4096 - cycle`

I think you mean 4096 - cyclePosition? cyclePosition has where we are in the current cycle, cycle is just the absolute number of cycles (remember, it starts from zero!) This field can be retrieved from the aforementioned RPC.

**Comment by vishakh** [comment]
@ba205 Thanks, I updated the spec.

**Comment by ivanopagano** [comment]
Not sure how we do the last point: get from the node baking rights for blocks yet to be stored
