### ISSUE TITLE
Support SSL for Postgres connections

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#608]
Conseil doesn't appear to run when SSL is required by a database. This should be fixed.

**Comment by ivanopagano** [comment]
To support SSL, you need to match the corresponding properties - as required by the server config - within the `lorre.db` and `conseil.db` configurations

Relevant config entries for our test instance where
```coffee
    serverName: "server-host-address"
    ssl: true
    sslMode: "require"
    databaseName: "database"
    user: "user"
    password: "password"
    portNumber: 25060
    reWriteBatchedInserts: true
```

I'll add other related entries (like ca-cert and stuff) in a PR with updated docs
