### ISSUE TITLE
Handle babylon additions to michelson

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#618]
The currently available contracts after the babylon upgrade contains new instructions not currently handled by the micheline/michelson parser.

Therefore Lorre fails to parse contracts like the following:

```
11:46:13.569 [lorre-system-akka.actor.default-dispatcher-4] ERROR  t.c.conseil.tezos.TezosNodeOperator  - interface tech.cryptonomic.conseil.tezos.michelson.dto.MichelsonInstruction: Error during conversion of {"entrypoint":"default","value":{"int":"22"}}
io.circe.DecodingFailure$$anon$2: Attempt to decode value on failed cursor: DownField(bytes)
```

**Comment by ivanopagano** [comment]
Relevant article:
https://blog.nomadic-labs.com/michelson-updates-in-005.html

**Comment by vishakh** [comment]
As part of this effort, we should resolve all failing Micheline parsing.
