### ISSUE TITLE
accounts_history table updates

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#619]
- [x] remove `manager` field
- [x] remove `delegate_setable` field
- [x] remove `spendable` field
- [ ] remove `script` - it will never change
- [x] `counter` doesn't seem to update
- [ ] add `cycle` field
- [ ] update metadata to read "Account History" for both `displayName` and `displayNamePlural`

**Comment by vishakh** [comment]
@anonymoussprocket Changing a lot of these fields will make `accounts_history` inconsistent with `accounts`. Is this intentional?

**Comment by anonymoussprocket** [comment]
This table contains changes. `script` can never change once deployed.

`manager`, etc are deprecated, they will never change going forward and it would be fine to trash the changes from pre-P005 era.

`isBaker` has a ticket for the accounts table: #604.

**Comment by vishakh** [comment]
@anonymoussprocket  The original intention was to test the new table and then kill `accounts` once `accounts_history` was proven to be good, with the further intention of making certain other tables temporal as well. If we change the shape of the new table, this might not be possible. Is tat OK with you?

Regarding deprecated fields, they do capture data that was available on the blockchain. So far we have tried to capture Tezos RPC data as expansively as possible. This would be a change in philosophy. Is that OK with you? If a future protocol upgrade further changes the way accounts work, would we then retrospectively delete some of the fields active now?

**Comment by vishakh** [comment]
@anonymoussprocket `isBaker` potentially changes the architecture of the application so it should be done as a dedicated ticket.

**Comment by vishakh** [comment]
As discussed with @anonymoussprocket, we are going ahead with the changes he specified.
