### ISSUE TITLE
Record roll count

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#631]
- [ ] Store roll count in `baker` table
- [ ] Store roll count in `baker_history` table
- [ ] Remove `rolls` table

**Comment by vishakh** [comment]
The implementer should verify the following assumptions:
- For each block, Lorre fetches data for all delegates, compares it to the data already in the database and, where it sees a difference, writes updated records into `delegates` and `delegates_history`. 
- For each block, Lorre fetches all roll counts and saves them into the database for the block.

If the above is correct, we want to instead:
- For each block Lorre should fetch the latest delegate information.
- It should also fetch the roll counts for the same block and combine it with the above.
- Where the data is different from what is already contained in the database, Lorre should add / updated records in `delegates_history` and `delegates`. 

The net effect will be:
- There will be no `rolls` table anymore.
- The `delegates` table will have a new column called `rolls`.
- The `delegates_history` table will have a new column called `rolls`.
