### ISSUE TITLE
Capture Tezos big_map contents

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#632]
The values contained in Tezos smart contract big_maps are especially useful since they contain things like token balances and payment addresses. We would therefore like to capture them in the Conseil database. 

## Phase 1

For this purpose, we should create two new tables.

The first should be called `big_maps` with the following columns:
- big_map_id: Numeric Tezos ID of a big_map
- key_type: Type of key
- value_type: Value type
- contract: Address of associated contract

The second should be called `big_map_contents` with the following columns:
- big_map_id: Numeric Tezos ID of a big_map
- key: Key of a map entry
- key_hash: Hash of the key
- value: Value of a map entry

Values should be inserted, amended or removed based on operation results. There is an example operation below from `babylonnet` which causes a new map to be initialized with an initial value. The contents of `big_map_diff` show an `alloc` and an `update` on big_map #22, i.e. the creation and updation of a big_map. 

The `alloc` action should trigger the following:
- New entry in `big_maps` with one entry corresponding to each address in `originated_contracts`.

The `update` action should trigger the following:
- Check for existing entry in `big_map_contents` and update it if one exists
- If there is no existing entry, add a new entry.

The 'remove' action should trigger the following:
-Find the integer id of the bigmap, given by "big_map" in the action
-Delete all rows in the database associated with those big_maps. Alternatively, we can have a flag "isRemoved" in the db, set this to true for all rows with this associated id.

The 'copy' action should trigger the following:
-Find the integer id using "source_big_map" in the database, copy the contents of that row(s) into objects
-Create new row(s) with those objects, but replace the integer id with "destination_big_map" in the payload instead.

## Phase 2

The `big_map_contents` table should be made temporal along the lines of the `accounts` table. 

## Example Tezos data

Extracted from https://tezos-dev.cryptonomic-infra.tech:443/chains/main/blocks/BMF66vw6H2rPD44kw6dnDv6fzPwUEfCyTC3bmbPkyR9UYtB9DMd/operations:

```json
{
                    "kind": "origination",
                    "source": "tz1bwsEWCwSEXdRvnJxvegQZKeX5dj6oKEys",
                    "fee": "150000",
                    "counter": "17",
                    "gas_limit": "400000",
                    "storage_limit": "10000",
                    "balance": "1000000",
                    "script": {...},
                    "metadata": {
                        "balance_updates": [
                            {
                                "kind": "contract",
                                "contract": "tz1bwsEWCwSEXdRvnJxvegQZKeX5dj6oKEys",
                                "change": "-150000"
                            },
                            {
                                "kind": "freezer",
                                "category": "fees",
                                "delegate": "tz1PirboZKFVqkfE45hVLpkpXaZtLk3mqC17",
                                "cycle": 9,
                                "change": "150000"
                            }
                        ],
                        "operation_result": {
                            "status": "applied",
                            "big_map_diff": [
                                {
                                    "action": "alloc",
                                    "big_map": "22",
                                    "key_type": {
                                        "prim": "address"
                                    },
                                    "value_type": {
                                        "prim": "pair",
                                        "args": [
                                            {
                                                "prim": "nat"
                                            },
                                            {
                                                "prim": "map",
                                                "args": [
                                                    {
                                                        "prim": "address"
                                                    },
                                                    {
                                                        "prim": "nat"
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                },
                                {
                                    "action": "update",
                                    "big_map": "22",
                                    "key_hash": "exprv6UsC1sN3Fk2XfgcJCL8NCerP5rCGy1PRESZAqr7L2JdzX55EN",
                                    "key": {
                                        "bytes": "0000b2e19a9e74440d86c59f13dab8a18ff873e889ea"
                                    },
                                    "value": {
                                        "prim": "Pair",
                                        "args": [
                                            {
                                                "int": "20"
                                            },
                                            []
                                        ]
                                    }
                                }
                            ],
                            "balance_updates": [
                                {
                                    "kind": "contract",
                                    "contract": "tz1bwsEWCwSEXdRvnJxvegQZKeX5dj6oKEys",
                                    "change": "-5333000"
                                },
                                {
                                    "kind": "contract",
                                    "contract": "tz1bwsEWCwSEXdRvnJxvegQZKeX5dj6oKEys",
                                    "change": "-257000"
                                },
                                {
                                    "kind": "contract",
                                    "contract": "tz1bwsEWCwSEXdRvnJxvegQZKeX5dj6oKEys",
                                    "change": "-1000000"
                                },
                                {
                                    "kind": "contract",
                                    "contract": "KT1DT9YwHdSbZuVuZDjd1SMUcfXm57R5bE9v",
                                    "change": "1000000"
                                }
                            ],
                            "originated_contracts": [
                                "KT1DT9YwHdSbZuVuZDjd1SMUcfXm57R5bE9v"
                            ],
                            "consumed_gas": "146770",
                            "storage_size": "5333",
                            "paid_storage_size_diff": "5333"
                        }
                    }
                }
```
## Fetching big_map data

Once this functionality is available, Conseil users could fetch big_map contents in the following manner:
- Query the `big_maps` table with the contract ID they are interested in.
- For each `big_map_id` value that comes back:
  - Fetch all values from `big_map_contents`

If they are looking for a specific key, they would use ConseilJS to generate a key hash. Using this key hash, they would perform the above routine but restrict their search to the given key hash.

**Comment by ivanopagano** [comment]
@vishakh 
Just to be sure, all of this only applies to the post-babylon update.
There's no such thing as alloc/update/remove/copy for the previous protocols' schema

Correct?

**Comment by vishakh** [comment]
Not sure, to be honest. :(

**Comment by ivanopagano** [comment]
It's just because the schema before didn't specify any "action" on big-maps, it was a "bare data field"
