### ISSUE TITLE
Record failure reason for operations that are not "applied"

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#655]
Here's one example of a failed operation, search the [results](https://tezos-prod.cryptonomic-infra.tech/chains/main/blocks/735195/operations) for `onrAgyCmm8JUxagqrga7PzP2VxjGJRkiZN1KyscDXsutLobELxF`. For more examples, use this [arronax report](https://arronax.io?e=Tezos%20Mainnet/operations&q=eyJmaWVsZHMiOlsidGltZXN0YW1wIiwiYmxvY2tfbGV2ZWwiLCJzb3VyY2UiLCJkZXN0aW5hdGlvbiIsImFtb3VudCIsImtpbmQiLCJmZWUiLCJzdGF0dXMiLCJvcGVyYXRpb25fZ3JvdXBfaGFzaCJdLCJwcmVkaWNhdGVzIjpbeyJmaWVsZCI6InRpbWVzdGFtcCIsIm9wZXJhdGlvbiI6ImFmdGVyIiwic2V0IjpbMTU3NTE3NjQwMDAwMF0sImludmVyc2UiOmZhbHNlfSx7ImZpZWxkIjoic3RhdHVzIiwib3BlcmF0aW9uIjoiZXEiLCJzZXQiOlsiYXBwbGllZCJdLCJpbnZlcnNlIjp0cnVlfV0sIm9yZGVyQnkiOlt7ImZpZWxkIjoidGltZXN0YW1wIiwiZGlyZWN0aW9uIjoiZGVzYyJ9XSwiYWdncmVnYXRpb24iOltdLCJsaW1pdCI6MTAwMH0). Review the results for more examples than only `Transaction`, `Backtracked`.

**Comment by vishakh** [comment]
Failure reasons are not recorded on chain unless you can find a way to fetch them somehow via RPC.

**Comment by vishakh** [comment]
Apparently they are recorded. Will update the spec accordingly.

**Comment by vishakh** [comment]
Until #672 is resolved and we look into vector types, we should avoid creating a new table. Instead, for each operation, we can concatenate all the failures and put the value in a new column called `failures` in the `operations` table.
