### ISSUE TITLE
Evaluate Lorre compatibility w/LabNet

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#660]
Run a Lorre test against [LabNet](https://forum.tezosagora.org/t/introducing-labnet-a-rapid-iteration-testnet-for-tezos/1522) by TQTezos.

**Comment by vishakh** [comment]
@anonymoussprocket We should first do some internal infra work to point an env to labnet.

**Comment by vishakh** [comment]
@bhaskarkishore Let's create a new env in our new infra.

**Comment by vishakh** [comment]
Nothing to be done here after evaluation.
