### ISSUE TITLE
Record account activation balance

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#663]
Consider `metadata.balance_updates[0].change` of operation [oonmqc4t98bvLQNMBBT1XqtU3WtsZ49tL14dr9uyeEFGHq5kEs3](https://tezos-prod.cryptonomic-infra.tech/chains/main/blocks/1896/operations/) as an example.

**Comment by vishakh** [comment]
```sql
select 
	operation_group_hash,
	change
from 
	tezos.balance_updates 
where 
	operation_group_hash = 'oonmqc4t98bvLQNMBBT1XqtU3WtsZ49tL14dr9uyeEFGHq5kEs3';
```

![image](https://user-images.githubusercontent.com/931163/72252142-d34d4300-3624-11ea-857f-d2a9aacf3ef1.png)

@anonymoussprocket  Do we still need a change?

**Comment by anonymoussprocket** [comment]
Can't confirm in arronax

**Comment by vishakh** [comment]
Opened #673 to fix performance issue preventing you from looking at it in Arronax.

**Comment by vishakh** [comment]
@anonymoussprocket Could you please check now?

**Comment by vishakh** [comment]
Closing as there was no response.
