### ISSUE TITLE
Record all Tezos node RPC queries

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#677]
In order to help with the https://github.com/simplestaking/tezedge project and potentially gain massive performance gains for Lorre, we should prepare a list of all node RPC queries which can be handed over to @jurajselep. 

As a follow up action, once @jurajselep confirms all the RPC calls we need are available, we can test Lorre against the Tezos Rust node.

**Comment by jurajselep** [comment]
Great, Thanks

**Comment by piotrkosecki** [comment]
I've managed to gather endpoints which were called by Lorre and aggregated them, replacing the hash depending on the length: 

Important think to remember is that block_hash/head can have `~` character at the end, and number(X) following it means that we are referring to the block X levels earlier, for example head~100 will mean a block which level is head_level - 100.

```
GET chains/main/blocks/<block_hash>
GET chains/main/blocks/<block_hash>/context/contracts/<hash>
GET chains/main/blocks/<block_hash>/context/delegates/<hash>
GET chains/main/blocks/<block_hash>/helpers/baking_rights
GET chains/main/blocks/<block_hash>/helpers/endorsing_rights
GET chains/main/blocks/<block_hash>/operations
GET chains/main/blocks/<block_hash>/votes/ballot_list
GET chains/main/blocks/<block_hash>/votes/current_proposal
GET chains/main/blocks/<block_hash>/votes/current_quorum
GET chains/main/blocks/<block_hash>/votes/listings
GET chains/main/blocks/<block_hash>/votes/proposals
GET chains/main/blocks/head/helpers/baking_rights
GET chains/main/blocks/head/helpers/endorsing_rights
GET chains/main/blocks/head~
```

**Comment by ivanopagano** [comment]
> Important think to remember is that block_hash/head can have `~` character at the end, and number(X) following it means that we are referring to the block X levels earlier, for example head~100 will mean a block which level is head_level - 100.

We also probably need to refer to a block using offsets on the endpoints that uses `block_hash`, too, not only from `head`

**Comment by vishakh** [comment]
@jurajselep Closing this for now. Let us know if you need anything else.

**Comment by jurajselep** [comment]
Great Thanks
