### ISSUE TITLE
Record token balances in the Conseil database

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#679]
This follows up on #678.

Based on our registry of supported tokens, we would like to maintain a table of token balances.

At each big_map update, we should examine whether the related contracts are mentioned in the `registered_tokens` table and, if so, update the corresponding key's balance in the `token_balances' table. 

The form of the 'token_balances' table will be the following:

`token_id | address | balance | block_level | block_hash`

This table should be temporal in nature, just like `accounts_history`. 

TODO: Provide an example of a deployed FA1.2 token leave instructions on how to parse it.

**Comment by vishakh** [comment]
@anonymoussprocket Could you provide a link to an example FA1.2 deployed contract?

**Comment by anonymoussprocket** [comment]
Here's a helpful [arronax.io](https://arronax.io?e=Tezos%20Babylonnet/operations&q=eyJmaWVsZHMiOlsiYmxvY2tfbGV2ZWwiLCJkZXN0aW5hdGlvbiIsIm9wZXJhdGlvbl9ncm91cF9oYXNoIiwicGFyYW1ldGVycyJdLCJwcmVkaWNhdGVzIjpbeyJmaWVsZCI6ImRlc3RpbmF0aW9uIiwib3BlcmF0aW9uIjoiZXEiLCJzZXQiOlsiS1QxUm1EdVE2TGFURmZMclZ0S05jQkprTWd2bm9wRUFUSnV4Il0sImludmVyc2UiOmZhbHNlfV0sIm9yZGVyQnkiOlt7ImZpZWxkIjoiYmxvY2tfbGV2ZWwiLCJkaXJlY3Rpb24iOiJkZXNjIn1dLCJhZ2dyZWdhdGlvbiI6W10sImxpbWl0IjoxMDAwfQ) report

**Comment by ivanopagano** [comment]
Are the new balances somehow included in the transaction update (in the big_map?) or should we compute the new value out of the diff data and the existing token-balance entry?

**Comment by vishakh** [comment]
@ivanopagano Now that I think about it, it's best to first build a non-temporal table. 

You can proceed either way and pick the one you see most fit. However, I think it will be best to get it from the transaction updates as the token balances are fully reflected in the big_maps.

**Comment by ivanopagano** [comment]
> Here's a helpful [arronax.io](https://arronax.io?e=Tezos%20Babylonnet/operations&q=eyJmaWVsZHMiOlsiYmxvY2tfbGV2ZWwiLCJkZXN0aW5hdGlvbiIsIm9wZXJhdGlvbl9ncm91cF9oYXNoIiwicGFyYW1ldGVycyJdLCJwcmVkaWNhdGVzIjpbeyJmaWVsZCI6ImRlc3RpbmF0aW9uIiwib3BlcmF0aW9uIjoiZXEiLCJzZXQiOlsiS1QxUm1EdVE2TGFURmZMclZ0S05jQkprTWd2bm9wRUFUSnV4Il0sImludmVyc2UiOmZhbHNlfV0sIm9yZGVyQnkiOlt7ImZpZWxkIjoiYmxvY2tfbGV2ZWwiLCJkaXJlY3Rpb24iOiJkZXNjIn1dLCJhZ2dyZWdhdGlvbiI6W10sImxpbWl0IjoxMDAwfQ) report

And here's the originating block's [query](https://arronax.io?e=Tezos%20Babylonnet/operations&q=eyJmaWVsZHMiOlsiYmxvY2tfbGV2ZWwiLCJibG9ja19oYXNoIiwiZGVzdGluYXRpb24iLCJvcGVyYXRpb25fZ3JvdXBfaGFzaCIsInBhcmFtZXRlcnMiLCJraW5kIl0sInByZWRpY2F0ZXMiOlt7ImZpZWxkIjoib3JpZ2luYXRlZF9jb250cmFjdHMiLCJvcGVyYXRpb24iOiJsaWtlIiwic2V0IjpbIktUMVJtRHVRNkxhVEZmTHJWdEtOY0JKa01ndm5vcEVBVEp1eCJdLCJpbnZlcnNlIjpmYWxzZX1dLCJvcmRlckJ5IjpbeyJmaWVsZCI6ImJsb2NrX2xldmVsIiwiZGlyZWN0aW9uIjoiZGVzYyJ9XSwiYWdncmVnYXRpb24iOltdLCJsaW1pdCI6MTAwMH0)
