### ISSUE TITLE
Michelson contract fails to convert

### ISSUE THREAD

**Issue by dorians** [Cryptonomic/Conseil#684]
https://smart-contracts-micheline-michelson-translator-for-tezos.scalac.io which uses our JS parser fails for parsing following contract: 
https://tezos-prod.cryptonomic-infra.tech/chains/main/blocks/BLGkUWx1PWPMKnrc1PjGECneRKK7AA8SKg1CN1YfTX1aLQEWVq4/context/contracts/KT19ZSNkZ1wNdmHRQ9tYVgmMChmpqCyCus2M

This contract comes from Conseil but it looks the same as an original contract from Tezos. Therefore it should be parsable so there's probably a bug in our JS parser.

**Comment by vishakh** [comment]
Closed as this was actually a ConseilJS bug.
