### ISSUE TITLE
Baking/Endorsing Rights estimated_time not correct

### ISSUE THREAD

**Issue by godenzim** [Cryptonomic/Conseil#694]
We noticed that the `estimated_time` field returned from the `/baking_rewards` and `endorsing_rewards` endpoints are not correct.

for example, at this time, if we query `/endorsing_rewards` with:

```json
{
    "fields": [
        "estimated_time",
        "level"
    ],
    "predicates": [
        {
            "field": "level",
            "operation": "eq",
            "set": [
                834213
            ],
            "inverse": false
        },
        {
            "field": "delegate",
            "operation": "eq",
            "set": [
                "tz1MJx9vhaNRSimcuXPK2rW4fLccQnDAnVKJ"
            ],
            "inverse": false
        }
    ],
    "limit": 1
}
```

The response contains:

```json
[
    {
        "estimated_time": 1582283724000,
        "level": 834213
    }
]
```

Where `1582283724000` converts to `Fri Feb 21 2020 11:15:24` UTC.

But if we get the endorsing rights from a node at `chains/main/blocks/head/helpers/endorsing_rights?delegate=tz1MJx9vhaNRSimcuXPK2rW4fLccQnDAnVKJ&cycle=203`

We get the following:

```json
--- CUT ---
    {
        "level": 834213,
        "delegate": "tz1MJx9vhaNRSimcuXPK2rW4fLccQnDAnVKJ",
        "slots": [
            22
        ],
        "estimated_time": "2020-02-21T14:58:00Z"
    },
--- CUT ---
```

Which has a completely different `estimated_time`.

The same can be said about the baking rights estimated time.

**Comment by vishakh** [comment]
@godenzim  Unfortunately, by the time we tried to reproduce your query, the block had been baked so we could not verify the data. Could you provide another such example for a future block?

**Comment by vishakh** [comment]
@piotrkosecki Could you please have a look?

Here's another example:

https://arronax.io?e=Tezos%20Mainnet/endorsing_rights&q=eyJmaWVsZHMiOlsibGV2ZWwiLCJzbG90IiwiZGVsZWdhdGUiLCJlc3RpbWF0ZWRfdGltZSIsImN5Y2xlIl0sInByZWRpY2F0ZXMiOltdLCJvcmRlckJ5IjpbeyJmaWVsZCI6ImxldmVsIiwiZGlyZWN0aW9uIjoiZGVzYyJ9XSwiYWdncmVnYXRpb24iOltdLCJsaW1pdCI6MTAwMH0 produced the following data: 
![image](https://user-images.githubusercontent.com/931163/75068348-01902f00-54bd-11ea-9d09-17086afdf2b7.png)

However, this is what I got back from an RPC call:

![image](https://user-images.githubusercontent.com/931163/75068398-1bca0d00-54bd-11ea-95f3-49186c207a35.png)

Observe the timestamps are slightly different. 

Could you please confirm Lorre is correctly saving down the estimated times it received from the Tezos node?

**Comment by piotrkosecki** [comment]
I've investigated the issue and it looks like `estimated_time` often changes:
<img width="1058" alt="Screenshot 2020-02-24 at 10 10 05" src="https://user-images.githubusercontent.com/2283610/75145860-1dccdf80-56fa-11ea-87f8-10d7f7a1ecdb.png">
and 1,5h later the estimated time is different:
<img width="1054" alt="Screenshot 2020-02-24 at 11 32 52" src="https://user-images.githubusercontent.com/2283610/75145902-363cfa00-56fa-11ea-9037-3fc54793082e.png">

I don't think it is currently possible for us to update every time `estimated_time` changes, and longer till block, the more this time will change.

**Comment by vishakh** [comment]
@godenzim Since the time estimate is dynamic and it's very expensive to constantly update it, is status quo ok?

**Comment by godenzim** [comment]
@vishakh, sorry for the late reply, this is a bit unfortunate, since we rely on this timestamp to show the next endorsing and baking right time. Is there no way to make just the next one more precise instead of all of them?

**Comment by vishakh** [comment]
Yes, since you need something so specific we can do it. It would be a
problem to update all records but certainly we can do the upcoming ones.

We'll get on this soon.

**Comment by vishakh** [comment]
@piotrkosecki What's the best way to refresh the estimated time for just the upcoming blocks?

**Comment by piotrkosecki** [comment]
So this is important when the Lorre is already in sync so we shouldn't care about future baking/endorsing rights for blocks that are already there but not processed by Lorre, right?

I was thinking that after the main process reaches head we could do this update for the next X blocks.
I don't have a reasonable value of X right now, but I could make it depend on config. 

What do you think about this approach @vishakh ?

**Comment by vishakh** [comment]
> So this is important when the Lorre is already in sync so we shouldn't care about future baking/endorsing rights for blocks that are already there but not processed by Lorre, right?

Correct.

I think you suggestion is good. We can go ahead with this ticket.
