### ISSUE TITLE
The registered tokens file needs be mandatory?

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#702]
Currently the token contracts are stored and read from a "network-specific" csv configuration file.

If the file is not available, Lorre currently doesn't start.

I suggest to make it optional, such that no token ledger would be loaded if the file is missing, possibly issuing a warn on the logs.

**Comment by vishakh** [comment]
I think it's good to keep it mandatory but with a very helpful error message. This ensures there are no phantom features that people miss. 

@anonymoussprocket @bhaskarkishore @piotrkosecki  What do you think?

**Comment by piotrkosecki** [comment]
> If the file is not available, Lorre currently doesn't start.

Thats not true, Lorre still starts when file is not present, but it shows an error.

**Comment by ivanopagano** [comment]
> > If the file is not available, Lorre currently doesn't start.
> 
> Thats not true, Lorre still starts when file is not present, but it shows an error.

Then I conflated a separate issue with that, sorry.

Closing
