### ISSUE TITLE
Roll and vote counts seems to be incorrectly matching

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#706]
![image](https://user-images.githubusercontent.com/1067461/76083740-8cd5ee00-5fae-11ea-9a9f-ae441c4d002a.png)

Rolls seems correct but votes not.
It's not likely that the two values would match.

Vote count should show instances of each vote, rolls the number of stake-rolls that voted.

We should verify were the data is taken, and how the things are counted.

**Comment by vishakh** [comment]
Closed in favor of #717.
