### ISSUE TITLE
Ability to get testnet faucet data

### ISSUE THREAD

**Issue by Taaseen-Ali** [Cryptonomic/Conseil#714]
Currently it is possible to retrieve data on how many mainnet fundraiser accounts have been activated, however, there is no way to view how many testnet faucet accounts have been activated. This information could be potentially useful for a user.

**Comment by vishakh** [comment]
@Taaseen-Ali Can you remind us why we needed this?

**Comment by vishakh** [comment]
Closing because of no follow up.
