### ISSUE TITLE
Fix yay, nay and pass counts in governance table

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#717]
The `governance` table columns `yay_count`, `nay_count` and `pass_count` are duplicates of `yay_rolls`, `nay_rolls` and `pass_rolls` respectively. Instead of storing the number of rolls that voted yes, no or pass, the former should store the number of ballot operations for yes, no and pass.

Modified algorithm for these columns:
1. For the current block in Lorre, obtain the current `cycle`. 
1. Fetch all `ballot` operations belong to the current `cycle`.
1. Group by the `vote` column into yay, nay and pass counts.
1. Populate above counts into table.

Alternatively, fetch the counts as of the previous block and simply add the counts for the current block.

**Comment by anonymoussprocket** [comment]
Is this related to #706? If so, close it please.
