### ISSUE TITLE
Create a `tezos_names` table

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#723]
Conseil should be integrated with the Tezos Name Service (TNS).

TNS maps commonsensical strings to Tezos addreses which allows general ease of use, e.g. send funds to `vishakh.xtz` instead of `tz1....`. 

Lorre will need to read the contents of a configured smart contract and, similar to the token balances ticket, populate entries [from a big_map](https://github.com/Cryptonomic/Smart-Contracts/blob/68a28dccd8b9cd78becd7a525fa56b7c02f70aba/tezos/smartpy/tns/tns-domainmanager.py#L10) into a table with the following schema:

`Key|Name|Owner|Resolver|RegisteredAt|RegistrationPeriod|Modified`

The [SmartPy code](https://github.com/Cryptonomic/Smart-Contracts/blob/tns/tezos/smartpy/tns/tns-domainmanager.py) and [Michelson translation](https://github.com/Cryptonomic/Smart-Contracts/blob/tns/tezos/smartpy/tns/tns-domainmanager.michelson) for the contract can be found on GitHub.

**Comment by vishakh** [comment]
@anonymoussprocket Could you please provide an example contract with entries from the testnet? Also, can you recommend a database schema?

**Comment by ivanopagano** [comment]
Is there a [semi-]formal spec for different TNS contracts, just like for standard tokens?

**Comment by anonymoussprocket** [comment]
No, we wrote a contract that we thing has a good design.

**Comment by vishakh** [comment]
> Is there a [semi-]formal spec for different TNS contracts, just like for standard tokens?

Links to the smart contract code are now in the issue description.

**Comment by ivanopagano** [comment]
@vishakh @anonymoussprocket 
What's the

`Key` of the database row supposed to be? Is that the key entry in the big map (hashed)?
Or is it a generated database sequenced PK?
