### ISSUE TITLE
Record baker block reward

### ISSUE THREAD

**Issue by Messer4** [Cryptonomic/Conseil#734]
The data on baking block rewards is now missing from the Conseil db. Do you have any plans to add this very important value and if you do when? Thanks.

**Comment by vishakh** [comment]
Could you say precisely what you mean by "baking block rewards"?

**Comment by Messer4** [comment]
What I mean is the rewards that bakers receive for producing blocks in Tezos.

**Comment by vishakh** [comment]
You should see it in the `balance_updates` table with the following filters:

```sql
select * from tezos.balance_updates where category='rewards' and source='block';
```

Let us know if you want it in a different form.

**Comment by vishakh** [comment]
Assuming this is resolved.
