### ISSUE TITLE
Make balance_updates easier to use

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#766]
- [ ] The `contract` column of `balance_updates` contains nulls. It should always be populated so we can get all balance updates for a given account ID. Where the column has null values, the value of the `delegate` column should be copied over. 

- [ ] `contract` should be renamed to `account_id` to make the terminology consistent with the other tables.

- [ ] The `delegate` column should be removed if it does not add any information beyond what `account_id` does.

- [ ] `block_id`, `block_level`, `cycle` and `period` should be added to the table.

- [ ] It's possible to view balance updates data in Arronax because there are no indexes to help with the display. We should index the following columns in the table:
- `account_id`
- `block_level`

Reference: https://github.com/Cryptonomic/Conseil/wiki/The-balance_updates-table

**Comment by ivanopagano** [comment]
@vishakh I'm wondering if having a `block_id` reference in the balance makes the `source_hash` column irrelevant.
It's populated with the block hash (i.e. the block_id) for block-related updates. But now we can check the block_id instead.
It's just a matter of reading the kind of update to understand if there's a specific operation involved...
