### ISSUE TITLE
Conseil should expose a route listing all available blockchain protocols

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Conseil#77]
The Conseil REST API should expose a route called '/info' which returns metadata about the running Conseil instance. As a start, it should return all blockchains and platform supported by the given Conseil instance. This route can be used by client applications, e.g. Arronax, to deduce all available platforms. 

This is a rough example of a return value of the route:
```json
{
	"platforms": [

	{
	"platform": "tezos",
	"network": "zeronet"
	}

	]
}
```

**Comment by vishakh** [comment]
The Conseil REST API should expose a route called '/info' which returns metadata about the running Conseil instance. As a start, it should return all blockchains and platform supported by the given Conseil instance. This route can be used by client applications, e.g. Arronax, to deduce all available platforms. 

This is a rough example of a return value of the route:
```json
{
	"platforms": [

	{
	"platform": "tezos",
	"network": "zeronet"
	}

	]
}
```

**Comment by anonymoussprocket** [comment]
Superseded by #215
