### ISSUE TITLE
Registered tokens table update

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#784]
Token contracts should store scale. That is the power of 10 that should be used to interpret the values in the balance map.

If account balance is 1 and scale is 0, then token balance is 1. If account balance is 1 and scale is 6, the token balance is 0.000001.

**Comment by piotrkosecki** [comment]
I think I don't get the idea of this update. Can you clarify some things for me @anonymoussprocket ?
Few questions:
- which table do you exactly have in mind? do you mean `known_addresses` table?(it contains only `account_id` and `alias`)
- what do you mean by `balance map`?
- based on what should we store the scale? I believe that tezos node currently gives us balances in the same format.
