### ISSUE TITLE
Inconsistent values for parameters and parameters_micheline

### ISSUE THREAD

**Issue by godenzim** [Cryptonomic/Conseil#852]
Sending the following query to the `/v2/data/tezos/mainnet/operations` endpoint:

```json
{
    "fields": ["parameters", "parameters_micheline"],
    "predicates": [
        {
            "field": "operation_group_hash",
            "operation": "eq",
            "set": [
                "opKYnbone62mtx6tNhkbPRbawmHzXZXwuAmHoSZKtGjhtUjpSaM"
            ],
            "inverse": false
        }
    ]
}
```

results in:

```json
[
    {
        "parameters": "Pair \"tz1XVRuKfcbCGWK4pvJaxyFAN7ayhoFtdWEt\" (Pair \"tz1SbC5uEwQ2114PhHooPhLr8T5NLEghbToz\" 1)",
        "parameters_micheline": "[{\"prim\":\"DROP\"},{\"prim\":\"NIL\",\"args\":[{\"prim\":\"operation\"}]},{\"prim\":\"PUSH\",\"args\":[{\"prim\":\"key_hash\"},{\"string\":\"tz1TG2LGuJYpRPa3AAW6bugGgy2LiyxrUN7w\"}]},{\"prim\":\"IMPLICIT_ACCOUNT\"},{\"prim\":\"PUSH\",\"args\":[{\"prim\":\"mutez\"},{\"int\":\"60000000\"}]},{\"prim\":\"UNIT\"},{\"prim\":\"TRANSFER_TOKENS\"},{\"prim\":\"CONS\"}]"
    }
]
```

The `parameters_micheline` value is clearly wrong since it should be just the micheline version of the `parameters` value. Not sure if this is happening only for this specific operation or if there are other inconsistencies, I only found this one so far.

**Comment by ivanopagano** [comment]
Thank you for pointing out, we'll investigate the issue

**Comment by ivanopagano** [comment]
After a first analysis I'm considering that the traversal of the operations to update with michelson conversions is actually writing on every good transaction in the block

![image](https://user-images.githubusercontent.com/1067461/84776658-e18ef900-afe0-11ea-9e51-7951055de780.png)

**Comment by ivanopagano** [comment]
I'm working to have a unit test reproducing the bug

**Comment by ivanopagano** [comment]
The issue is already solved in the upcoming release of conseil.
We have to kindly ask you for some patience, we're almost there.
@godenzim 

For the moment, all I can say is to **avoid considering the parameters fields** as a reliable field for any computation
