### ISSUE TITLE
Update Jackson-databind to 2.9.10.6 

### ISSUE THREAD

**Issue by thanlok** [Cryptonomic/Conseil#902]
The official Jack-databind has released a fix on possible vulnerabilities about the classes that allow performing non-accessible methods or accessing non-accessible data. Please update the dependency version to 2.9.10.6 or above. 

The link to the related issue: [https://medium.com/@cowtowncoder/jackson-2-10-safe-default-typing-2d018f0ce2ba](https://medium.com/@cowtowncoder/jackson-2-10-safe-default-typing-2d018f0ce2ba)

The link to official fix:[https://github.com/FasterXML/jackson-databind/issues/2814](https://github.com/FasterXML/jackson-databind/issues/2814)

**Comment by ivanopagano** [comment]
Closed by #905
