### ISSUE TITLE
Conseil logging needs improvements

### ISSUE THREAD

**Issue by ivanopagano** [Cryptonomic/Conseil#942]
Latest testing on a local node lead to an app failure which stopped with little to no information to figure out the cause.

Here is the output
```
15:13:35.809 [run-main-0]                        INFO  t.c.c.indexer.tezos.TezosIndexer     [?:?] - Successfully made initial connection to Tezos
15:13:36.065 [run-main-0]                        INFO  t.cryptonomic.conseil.indexer.Lorre$ [?:?] - Doing clean-up.
15:13:36.066 [run-main-0]                        INFO  com.zaxxer.hikari.HikariDataSource   [?:?] - lorre.db - Shutdown initiated...
15:13:36.075 [run-main-0]                        INFO  com.zaxxer.hikari.HikariDataSource   [?:?] - lorre.db - Shutdown completed.
15:13:36.131 [-akka.actor.default-dispatcher-4]  INFO  RightsFetcher                        [?:?] - Fetching future baking and endorsing rights
15:13:36.177 [run-main-0]                        INFO  t.cryptonomic.conseil.indexer.Lorre$ [?:?] - All things closed.
[error] (run-main-0) io.circe.ParsingFailure: expected json value got 'Failed...' (line 1, column 1)
[error] io.circe.ParsingFailure: expected json value got 'Failed...' (line 1, column 1)
[error] Nonzero exit code: 1
[error] (lorre / runTask) Nonzero exit code: 1
[error] Total time: 4 s, completed Oct 22, 2020, 3:13:36 PM
[warn] Thread[Logback shutdown hook [default],5,run-main-group-0] loading ch.qos.logback.core.LifeCycleManager after test or run has completed. This is a likely resource leak
```

Here we can see a few improvements possible:
 1. the Parsing Failure had no stack trace to use for identifying the actual reason, which is not obvious from the output
 2. the placeholders to show source file and line of the output are empty
 3. (not shown here) there is no immediate way to verify which calls are actually made from conseil to the chain node

I'm gonna elaborate on the above list and possibly open separate sub-issues to find solutions for each

 1. we need to verify if Circe parsing errors have a lazy/missing stack-trace as commonly happen with scala libraries, to improve performance when handling errors with typed approach (e.g. Either[Err, T]). Or if the stack's there but the runtime won't show that upon an uncaught error reaching the main app thread loop
 2. there are a couple of alternatives in scala which provide source-level information to the logs, and try to improve the stack-traces. We might look at a couple of alternatives, and evaluate the impact to the current design (which is based on typesafe logging, and akka logging). Possible alternatives to evaluate
    * [sourcecode library](https://github.com/lihaoyi/sourcecode#logging) which manually allows to extract the info at compile time and add as part of the the output
    * [airframe logging](https://wvlet.org/airframe/docs/airframe-log) a lightweight alternative which includes source code locations and it's based on java.util.logging and compatible with sl4j
 3. There is a way to "probe" every element passing through the akka-stream which makes the batched queries. We can use a flag to turn on this extra log and "trace" the http communication enough to get additional visibility into the possible issues

**Comment by ivanopagano** [comment]
@vishakh @piotrkosecki @bhaskarkishore please contribute to the discussion above.

I've already implemented a solution for `3`.

Looking for the best choice for `2`, given our current situation. We want feature parity with current logging if possible, and least disruption to the codebase

**Comment by vishakh** [comment]
@ivanopagano For (2), intuitively I prefer airframe-log as it's both lightweight and has a lighter touch. The sl4j compatibility is also nice.

**Comment by piotrkosecki** [comment]
I like the idea of improving logging failing requests. Something which would contain endpoint called and response would be really useful so we could check if the issue is easy to reproduce or just a one time thing that caused request to fail. 
Regarding 2. from what I saw airframe feels better documented, so I would vote for it.

**Comment by ivanopagano** [comment]
Going for airframe, I'll see what comes of it

Thank you both
