### ISSUE TITLE
Aggregations across multiple columns don't work

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Conseil#953]
[Example](https://arronax.io/tezos/mainnet/blocks/query/eyJmaWVsZHMiOlsibWV0YV92b3RpbmdfcGVyaW9kIiwibWV0YV9jeWNsZSIsImxldmVsIl0sInByZWRpY2F0ZXMiOlt7ImZpZWxkIjoidGltZXN0YW1wIiwib3BlcmF0aW9uIjoiYWZ0ZXIiLCJzZXQiOlsxNTc3ODU0ODAwMDAwXSwiaW52ZXJzZSI6ZmFsc2V9XSwib3JkZXJCeSI6W3siZmllbGQiOiJtZXRhX3ZvdGluZ19wZXJpb2QiLCJkaXJlY3Rpb24iOiJkZXNjIn1dLCJhZ2dyZWdhdGlvbiI6W3siZmllbGQiOiJtZXRhX2N5Y2xlIiwiZnVuY3Rpb24iOiJjb3VudCJ9LHsiZmllbGQiOiJsZXZlbCIsImZ1bmN0aW9uIjoiY291bnQifV0sImxpbWl0IjoxMDAwfQ)

**Comment by vishakh** [comment]
Needs investigation.
