### ISSUE TITLE
Best effort connections for Lorre

### ISSUE THREAD

**Issue by g574** [Cryptonomic/Conseil#992]
Hi There.
I have configured Lorre to connect to multiple tezos nodes:
```
platforms: [
  {
    name: "tezos"
    network: "mainnet"
    enabled: true
    node {
        protocol: "http",
        hostname: "server1",
        port: 8732
        path-prefix: ""
    }

    node {
        protocol: "https",
        hostname: "server2",
        port: 8732
        path-prefix: ""
    }

    node {
        protocol: "https",
        hostname: "server3",
        port: 8732
        path-prefix: ""
    }

    node {
        protocol: "https",
        hostname: "server4",
        port: 8732
        path-prefix: ""
    }

  }
]

lorre ...
```

I have realised that if one of them is not reachable then it does not start synchronising:
```
2021.04.21 12:02:51:666 [ERROR] tech.cryptonomic.conseil.indexer.tezos.TezosIndexer.checkTezosConnection:84 - Could not make initial connection to Tezos
...
```

Could it be changes in a way that it connects to any of the servers instead of trying to connect to all of them? I think it would make more sense.

**Comment by piotrkosecki** [comment]
Configuration you used will try to connect to the last node - we don't support multiple nodes. 
I don't think we should to be honest.  At given point in time nodes may present different data and it may lead to inconsistencies in the DB.

**Comment by g574** [comment]
OK, understood. Thanks a lot.
