### ISSUE TITLE
Handling tzip-16 compatible contracts

### ISSUE THREAD

**Issue by piotrkosecki** [Cryptonomic/Conseil#999]
As discussed with @bhaskarkishore metadata regarding tzip-16 contracts should be stored in the `known_addresses` table which now will look like this:
```
CREATE TABLE tezos.known_addresses (
    address character varying NOT NULL,
    alias character varying,
    name character varying,
    description character varying,
    version character varying,
    license_name character varying,
    license_details character varying,
    authors character varying,
    homepage character varying,
    source_tools character varying,
    source_location character varying,
    interfaces character varying,
    block_level bigint,
    timestamp timestamp without time zone,
    metadata_uri character varying,
    views character varying
);
```

The basic algorithm is rather simple to explain:
1. Parse operations parameters which match the tzip16 schema
2. Retrieve the metadata from URL (http/ipfs for now)
3. Store metadata in the modified `known_addresses` table.

@bhaskarkishore Is it ok, or am I missing something?

**Comment by vishakh** [comment]
@bhaskarkishore @piotrkosecki The purpose of the `known_addresses` table is simply to record labels for known addresses. We expect very few known addresses will actually be TZIP-16 compatible. Therefore, it might make more sense to store metadata in a new or other existing table. 

Since TZIP-16 is just a spec, implementations may vary a lot. Therefore, I don't expect it to be easy to identify relevant contracts. Have you found some reliable way to do this? If no, the `registered_tokens` table records the tokens we formally recognize. We could simply pull metadata for all TZIP-16 tokens mentioned in that table. 

Finally, how often is this information indexed? Is it part of the Lorre main loop? I don't think it makes sense to fetch this information during every iteration or maintain any history. Should this just run as a separate process which just periodically updates metadata, based on the conf file?

**Comment by piotrkosecki** [comment]
@vishakh 

> The purpose of the known_addresses table is simply to record labels for known addresses. We expect very few known addresses will actually be TZIP-16 compatible. Therefore, it might make more sense to store metadata in a new or other existing table.

I can adjust this and I can create separate table.

> Since TZIP-16 is just a spec, implementations may vary a lot. Therefore, I don't expect it to be easy to identify relevant contracts. Have you found some reliable way to do this? If no, the registered_tokens table records the tokens we formally recognize. We could simply pull metadata for all TZIP-16 tokens mentioned in that table.

I'll have more info about how reliable identifying is after more tests - I had limited test pool. If tests prove that it really is more complicated than I expected I think it will be good idea to use `registered_tokens` table.

> Finally, how often is this information indexed? Is it part of the Lorre main loop? I don't think it makes sense to fetch this information during every iteration or maintain any history. Should this just run as a separate process which just periodically updates metadata, based on the conf file?

For now it is in the Lorre main loop, because we can retrieve metadata only when contract is called.

**Comment by bhaskarkishore** [comment]
> @bhaskarkishore @piotrkosecki The purpose of the `known_addresses` table is simply to record labels for known addresses. We expect very few known addresses will actually be TZIP-16 compatible. Therefore, it might make more sense to store metadata in a new or other existing table.

This requirement came from @anonymoussprocket . I believe the goal here is to make it easier for ConseilJS to query relevant data.

> Since TZIP-16 is just a spec, implementations may vary a lot. Therefore, I don't expect it to be easy to identify relevant contracts. Have you found some reliable way to do this? If no, the `registered_tokens` table records the tokens we formally recognize. We could simply pull metadata for all TZIP-16 tokens mentioned in that table.

TZIP-16 expects a `%metadata` field in the contract storage. 

> Finally, how often is this information indexed? Is it part of the Lorre main loop? I don't think it makes sense to fetch this information during every iteration or maintain any history. Should this just run as a separate process which just periodically updates metadata, based on the conf file?

A second process to update the metadata periodically is fine. It might take more time to implement however.

**Comment by vishakh** [comment]
I think it would be unwise to update the metadata too frequently as it would greatly slow indexing for very little benefit. Therefore, a separate thread (not process) which runs every few hours would be better. 

Using `known_addresses` might be very illogical. `known_addresses` is populated manually while it seems we are trying to discover metadata automatically. 

Simply looking for a `metadata` field in storage might give us a lot of false positives. 

@piotrkosecki @bhaskarkishore Thoughts?

**Comment by bhaskarkishore** [comment]
> runs every few hours would be better.

We were thinking of refreshing every few hundred blocks that should translate into that time frame.

> Using `known_addresses` might be very illogical. `known_addresses` is populated manually while it seems we are trying to discover metadata automatically.
> 
> Simply looking for a `metadata` field in storage might give us a lot of false positives.
> 

I do not have a strong opinion on the table being repurposed nor why it should not. Please check with @anonymoussprocket .

**Comment by piotrkosecki** [comment]
After talking with @anonymoussprocket and investigating this thing further I have a proposal:

1. I'll create a metadata table with the data for information gathered from metadata.

2. I'll add `metadata_path` column to `registered_tokens` table which will hardcode path in the Michelson so it will allow us to easily extract metadata URI from the parameters for given tokens.

3. Then in the main Lorre loop when the contract will be called with the parameters I'll extract the metadata address, call it and store the data.

Downside: Every time when we will want to add new token we'll need to add knew token to `registered_tokens` CSV file for given network.

What do you think @vishakh @bhaskarkishore @anonymoussprocket ?

**Comment by vishakh** [comment]
Updated algorithm as agreed by @piotrkosecki @anonymoussprocket @bhaskarkishore @vishakh : 

The `registered_tokens` table should have the following new columns:
- `interfaces`: comma-separated list of implemented interfaces, e.g. `TZIP-16,TZIP-12`
- `isTZIP-16`: boolean indicating whether a given contract implements the metadata standard
- `isNFT`: Is this an NFT contract for which we want to index the metadata of the children?
- `metadata_type`: Can be `IPFS`, `Contract`, `Self` or `Web`.
- `metadata_big_map_id`: ID of the big_map containing the metadata for NFTs, etc. 
- `metadata_big_map_type`: Type of big_map metadata values, i.e.  `IPFS`, `Contract`, `Self` or `Web`. 
- `metadata_path`: Path to metadata in contract as applicable.

Depending on the configuration, Lorre should perform a sweep on the contracts table a few times a day in a separate thread. It should look for all records in `registered_tokens` with `isTZIP-16` set to true. For each record:
- If the metadata-type is other, fetch the metadata from IPFS and save it in the metadata table. 
- If the metadata-type is self, use the metadata_path to update the metadata table.
- If the metadata-type is contract, use the contract address and metadata_path to update the metadata table. 
- If the metadata-type is web, fetch the metadata from the web and update the metadata table.
- If isNFT is true, use the metadata_big_map_id and metadata_big_map_type to update the metadata table. 

Structure of the metadata table:
- `address`
- `raw_metadata`
- `name`
- `description`
- ..

Structure of the `nfts` table:
- `contract_address`
- `contract_name`
- `asset_type`
- `asset_location`
- `raw_metadata`
- ...
-
